### ISSUE TITLE
[Quest] Vashj'ir quest order 2 - Kelp'thar Forest

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3358]
**Links:**
https://www.wowhead.com/npc=41252/rendel-firetongue #3359
https://www.wowhead.com/npc=39667/adarrah 

- [x] Gimme Shelter! (missing) #3360
- [ ] Ain't Too Proud to Beg #3361

--------
npc https://www.wowhead.com/npc=39883/adarrah

- [x] A Taste For Tail (works)
- [x] A Girl's Best Friend (works)
- [x] Ophidophobia (works)
-------
https://www.wowhead.com/npc=40983/mack-fearsen
- [x] Nerve Tonic (works)
---------
https://www.wowhead.com/npc=46338/budd (missing) #3363
_for quests_
- [x] Oh, the Insanity (works) but drops extra #3407
- [x] Dah, Nunt... Dah, Nunt... #3408
- [ ] Tenuous Negotiations (**not ingame anymore**)
- [x] Shark Weak #3409
- [x] DUN-dun-DUN-dun-DUN-dun  #3410
Shallow End of the Gene Pool (**not ingame anymore**)
- [x] A Bone to Pick #3363
What? This Old Thing? (**not ingame anymore**)
- [x] Decisions, Decisions #3411

-------

https://www.wowhead.com/npc=41248/moanah-stormhoof
- [ ] Better Late Than Dead #3117
- [ ] The Abyssal Ride  #3118

**Need these fixing before i can continue questline report**  #3352

**Comment by Echinaceax** [comment]
@Rushor Priestelar aka @Tigerief is taking over my report now ok :)

**Comment by Priestelar** [comment]
Stunning! :)

**Comment by Priestelar** [comment]
Test

**Comment by Priestelar** [comment]
This report focuses strictly on this zone marked in the image as the Main Story quests are not doable in order to progress to other sections. Any quests that would be available in those sections are only side quests that should NOT yet be available.
![Vashjir](https://user-images.githubusercontent.com/16594771/67091579-4de4fe80-f1ad-11e9-84b3-6743422b872c.jpg) 


1 - [Quest] Call of Duty (Alliance) https://www.wowhead.com/quest=14482/call-of-duty - A long and entertaining scripted cutscene is supposed to unfold as the npcs guide you aboard the ship atm this is not implemented and the quest is auto set as completed when taking it.

2 - [Core] Sea Legs buff - You get this buff by default by being in this zone.

3 - [Quest] [Npc] Captain Taylor should only be giving out quests AFTER you complete https://www.wowhead.com/quest=25405/rest-for-the-weary

4 – [Quest] Helm’s Deep https://www.wowhead.com/quest=25946/helms-deep Quest is currently available to the alliance but it is a Horde ONLY quest.

5 – [Quest] On our own terms + All or nothing, These quests require the Npc Captain Taylor to act out 2 cutscenes that will cause his phasing to change https://www.wowhead.com/quest=25547/on-our-own-terms +  https://www.wowhead.com/quest=25558/all-or-nothing video of it here: https://youtu.be/hCvSBeUlk3c 

6 – [Npc] Erunak Stonespeaker, he is missing at this location in Shallow’s End. Here he is another quest giver. See section for Shallow’s End https://wowwiki.fandom.com/wiki/Erunak_Stonespeaker

7 – [Npc] [Ability] Speckled Sea Turtle – Giddyup! https://www.wowhead.com/npc=40223/speckled-sea-turtle#abilities this ability is not working at the moment.

8 – [Quest] Better late than dead https://www.wowhead.com/quest=25477/better-late-than-dead quest is not working or doable.

9 – [Npc] [Core] Using the quest item from entry number 8 causes your pet to be listed as hostile even though they aren’t. 
![WoWScrnShot_101819_112406](https://user-images.githubusercontent.com/16594771/67091451-ed55c180-f1ac-11e9-8b18-c7fa72c844ae.jpg)


10 – [Quest] Gimme Shelter https://www.wowhead.com/quest=25587/gimme-shelter Neither of the 2 parts of the quest work currently as shown in this video: https://youtu.be/1DR0sePfSY8 

11 – [Npc/Object] [Quest] Broken Bottle granting the quest A desperate plea is not implemented at the moment preventing this quest line https://www.wowhead.com/quest=25638/a-desperate-plea

12 – [Core] Pets get stuck in several sections of the terrain until you either manually move them out or resummons them as seen in this screenshot, it doesn’t matter which way I go the pet is “stuck” this happens a lot in the zone but this I know is something hard to fix but I’m just mentioning it here. This happens several times and then pets stop following/helping you in battles as well.
![WoWScrnShot_101819_125504](https://user-images.githubusercontent.com/16594771/67091473-f777c000-f1ac-11e9-999f-09b1fc1950fd.jpg)


13 – [Npc] Budd here is a skeleton I looked around on wowhead and wowpedia and couldn’t find any confirmation of him every being turned into a skeleton. Edit: Budd should only become a skeleton after you complete you finish the cutscene in the quest Dun dun dun dun! From number 15 in the report. 
![WoWScrnShot_101819_130024](https://user-images.githubusercontent.com/16594771/67091511-15ddbb80-f1ad-11e9-84e2-eea6ff91de7b.jpg)


14 – [Quest] Dun nant dah nunt! https://www.wowhead.com/quest=25657/dah-nunt-dah-nunt The quest is currently just an instant working or instant turn in and does not work like it should. As seen in this video: https://youtu.be/eOu8_EarD34

15 – [Quest] Dun dun dun dun! Not working but completable https://www.wowhead.com/quest=25670/dun-dun-dun-dun-dun-dun quest should have a cutscene as shown in the video here: https://youtu.be/yfKPx78rUcc 

16 – [Quest] [Item] Lady La-La’s Medallion https://www.wowhead.com/quest=25419/lady-la-las-medallion I killed several of these mobs for the 2 quests that send you to kill them and this item did NOT drop so I am assuming it is not implemented.

17 – [Quest] How disarming https://www.wowhead.com/quest=25883/how-disarming some of the tridents have imps spawned in them that should not be visible. 
![WoWScrnShot_101819_132503](https://user-images.githubusercontent.com/16594771/67091518-1d04c980-f1ad-11e9-819a-996fd8f4c370.jpg)


18 – [Npc] Shimmering grotto is currently not implemented, there are no npcs inside. This is supposed to be this way as Erunak Stonespeaker’s quests from Shallow’s End are not completed yet.
![WoWScrnShot_101819_132659](https://user-images.githubusercontent.com/16594771/67091527-22faaa80-f1ad-11e9-8586-2db3a5bfb8e3.jpg)

**What should happen?**

2 - The Sea legs buff should only be available after completing the quest called: Sea Legs https://www.wowhead.com/quest=24432/sea-legs If players run out of air, they are supposed to swim back to the quest givers to get air in the ship.

3 - As it stands now, Captain Taylor is giving out the following quests as soon as you reach the zone: Buy us some time https://www.wowhead.com/quest=25357/buy-us-some-time , Travelling on our stomachs https://www.wowhead.com/quest=25546/traveling-on-our-stomachs and Stormwind elite aquatic and land forces elithttps://www.wowhead.com/quest=25564/stormwind-elite-aquatic-and-land-forces

5 – These quests are currently not implemented and undoable since the quest giver does not transition into the next phases where the quests can be turned in or received.

6 – Erunak should be spawned here in order to hand in the quest: All or nothing and give you new quests to progress through the zone as he is responsible for the main story line of the zone.

7 – Using Giddyup! Does nothing, just does not work, it should give you a 100% movespeed boost while using the quest item from https://www.wowhead.com/quest=25477/better-late-than-dead Another note about the turtles: They should be normal mobs that can be attacked and skinned, however by default, hovering over the mob with your cursor will display a Gear icon like on objects that can be interacted with (NOT gamebreaking, just a side note).

8 – Quest should be doable, either by bringing the turtle to the quest giver or by it being attacked by the shark as shown in the video however at the moment neither work. I even tried to have a shark kill the turtle as in the screenshot. But this did not work either. This quest chain is *IMPORTANT* in order to get your seahorse mount in order to progress through the rest of the zone or else it takes inhumanely long.  
![WoWScrnShot_101819_112010](https://user-images.githubusercontent.com/16594771/67091403-d44d1080-f1ac-11e9-887a-7d6a20834633.jpg)

10 – Quest Npcs inside the new area should only be visible after completing Gimme Shelter.

For the most part a lot of the quests in the zone are available way before their prerequisites are done. Here is a “guide” that shows what quests are available at all times based on how far you are in the quest line as at the moment, main quests and side quests are both available without any progression needed. http://wow-pro.com/leveling_guides/arixans_alliance_leveling_guide_vashjir_80-82
I will be ending my report here as I am unable to progress with the main story and any side quests that should be available in the zone are not supposed to be available yet. Also the Seahorse Mount quest, The Abbyssal Ride - https://www.wowhead.com/quest=25371/the-abyssal-ride the quest is very unique as you can see in this video https://youtu.be/m95Tv9JVqEs But this quest is of High Priority for the zone as travelling around without it is impossible.

Conclusion: The zone still has a lot of work to do, but I am confident in your abilities Rushor :) Good luck and let me know if you need any more help on Vashj'ir

**Comment by Echinaceax** [comment]
reopening this atm
