### ISSUE TITLE
[Quest] Darkshore quest order - Darkshore

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3417]
**Links:**

https://www.wowhead.com/npc=42936/sentinel-cordressa-briarbow
- [x] Breaking Waves of Change  (fixed) #1109
- [x] Hero's Call: Darkshore! (works)
- [x] The Last Wave of Survivors (works)
------
https://www.wowhead.com/npc=33175/johnathan-staats
- [x] A Taste for Grouper (works)
--------
https://www.wowhead.com/npc=32972/serendia-oakwhisper
- [x] The Boon of the Seas (works)
-----
https://www.wowhead.com/npc=32978/tharnariun-treetender
- [x] The Corruption's Source (works)
----------
https://www.wowhead.com/npc=32977/wizbang-cranktoggle
- [x] Buzzbox 413 (works)
- [x] No Accounting for Taste (works)
- [x] Buzzbox 723 (works)
- [x] A Cure In The Dark (works)
-----
https://www.wowhead.com/npc=32979/gorbold-steelhand
- [x] An Ocean Not So Deep #1038
------
https://www.wowhead.com/npc=32971/ranger-glynda-nalshea
- [x] Threat from the Water #3418
- [x] The Final Flame of Bashal'Aran (requires A Cure In The Dark quest) (works)
- [x] The Shatterspear Invaders
----
https://www.wowhead.com/npc=32932/moon-priestess-tharill
- [x] Power Over the Tides #705
----
https://www.wowhead.com/npc=32960/volcor
- [x] A Lost Companion (works)
---
https://www.wowhead.com/npc=33126/seraphine
- [x] Twice Removed (fixed) #1051
---
https://www.wowhead.com/npc=33048/keeper-karithus
- [x] Unsavory Remedies (works)
- [x] Ritual Materials (fixed) #709
- [x] The Ritual Bond #2071
- [x] Grimclaw's Return (works)
---
https://www.wowhead.com/npc=32966/balthule-shadowstrike
- [x] Remnants of the Highborne
- [x] On the Brink
https://www.wowhead.com/npc=32965/sentinel-tysha-moonblade
- [x] Denying Manpower
- [x] Shatterspear Laborers
----
https://www.wowhead.com/npc=32963/lieutenant-morra-starbreeze
- [x] War Supplies
- [x] Strategic Strikes
- [x] The Front Line  (works but some issue) #1082
- [x] Ending the Threat #1047

- [x] Reason to worry 
- [x] Swift responce 
https://www.wowhead.com/npc=33055/alanndarian-nightsong
- [x] One Bitter Wish

https://www.wowhead.com/npc=32964/sentinel-aynasha
- [x] Timely arrival #1044
 ---
https://www.wowhead.com/npc=34041/mathas-wildwood
- [x] The Looting of Althalaxx
---
https://www.wowhead.com/npc=32987/corvine-moonrise
- [x] Three Hammers to Break 
- [x] Malfurion's Return
----
https://www.wowhead.com/npc=33232/archaeologist-hollee
- [x] The Last Refugee #1058
----
https://classic.wowhead.com/npc=6887/yalda
- [x] Coaxing the spirits #707
- [x] Call Down the Thunder https://github.com/WoWManiaUK/Blackwing-Lair/issues/3453
-----
https://www.wowhead.com/npc=33091/malfurion-stormrage
- [x] Mounting the Offensive
- [x] Protector of Ameth'Aran
- [x] The Emerald Dream
- [x] The Land Is in Their Blood
https://www.wowhead.com/npc=33117/elder-brownpaw
- [x] Mutual Aid https://github.com/WoWManiaUK/Blackwing-Lair/issues/1067
- [x] Soothing the Elements #712
- [x] The Blackwood Pledge
- [x] The Last Wildkin
https://www.wowhead.com/npc=33119/aroom
- [x] The wildkin's oath
- [x] Aroom's Farewell
- [x] Elune's Fire
---
https://www.wowhead.com/npc=33091/malfurion-stormrage
https://www.wowhead.com/npc=33166/thessera
- [x] The Waking Nightmare (fixed) #1749
- [x] Leaving the dream
----
https://www.wowhead.com/npc=33091/malfurion-stormrage
- [x] The Eye of All Storms #2082
---
https://classic.wowhead.com/npc=3694/sentinel-selarin
- [x] Against the wind
- [x] Call down the thunder
----
https://www.wowhead.com/npc=33112/selenn
- [x] Calming the Earth
- [x] Sworn to Protect
---
https://www.wowhead.com/npc=34402/balren-of-the-claw
- [x] Leave No Tracks https://github.com/WoWManiaUK/Blackwing-Lair/issues/1092
- [x] Stepping Up Surveillance https://github.com/WoWManiaUK/Blackwing-Lair/issues/1093
https://www.wowhead.com/npc=34404/larien
- [x] Unearthed Knowledge
- [x] Soggoth and Kronn
- [x] Ashes in Ashenvale

- [x] The Slumbering Ancients

- [x] What's Happening to the Blackwood Furbolg?
---
https://www.wowhead.com/npc=34301/kathrena-winterwisp
- [x] Consumed
- [x] The Seeds of Life
- [x] An Ounce of Prevention (fixed) #3395
- [ ] In Defense of Darkshore #3420
- [x] The Devourer of Darkshore #3421
----
https://www.wowhead.com/npc=32967/elder-brolg
- [x] The Bear's Paw
- [x] The Bear's Blessing
- [x] Cleansing the Afflicted (fixed) #2523
- [x] The Defiler

https://www.wowhead.com/npc=32968/gren-tornfur
- [x] Jadefire Braziers
----
https://www.wowhead.com/npc=34342/jr-archaeologist-ferd

- [x] Swamped Secrets
- [ ] The Titans' Terminal #1105
https://www.wowhead.com/npc=34340/archaeologist-groff
- [x] Sweeping Clean the Ruins
- [x] Got Some Flotsam?
- [x] A New Home
----
https://www.wowhead.com/npc=34498/darkscale-assassin
- [x] Naga In Our Midst 
- [x] The Darkscale Warlord (fixed) #1100
- [ ] The Offering to Azshara #1753
----
https://classic.wowhead.com/npc=11711/sentinel-aynasha
- [ ] One Shot. One Kill. #1108
-----
https://www.wowhead.com/npc=33176/kerlonian-evershade
- [ ] The Ancients' Ire #1046
-----

Bearer of Good Fortune #704
Writtings of the void #1083

**Comment by Rushor** [comment]
fixed

![I](https://i.imgur.com/rprHGB2.jpg)

once the Enraged Tidal Spirit isilled you can use the questitem http://cata.cavernoftime.com/item=44975 on them and a Tranquil Tidal Spirit will spawna nd give the credit.

**Comment by Rushor** [comment]
all quests from list http://cata.cavernoftime.com/quests=1.148
