### ISSUE TITLE
[Quest] Mount Hyjal quest order - (Horde) Mount Hyjal

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#3557]
**Links:**
https://wow.gamepedia.com/Mount_Hyjal_quests

- [x] Warchief's Command: Mount Hyjal!

**Neutural report** #3461

**Danah report for Shrine of Goldrinn** #1847
- [x] The Voice of Lo'Gosh
- [x] Howling Mad
- [x] Lycanthoth the Corruptor #3567 (quest works though) but not quest back #3568
- [x] The Shrine Reclaimed #3569

**Double NPCs Royce Duskwhisper and Rio Duran see phasing report** #1847

- [x] Cleaning House #3570
- [x] Lightning in a Bottle
- [x] Sweeping the Shelf
- [x] Into the Maw! 
**Neutural report** #3461
- [x] The Battle Is Won, The War Goes On
https://www.wowhead.com/npc=45244/farseer-krogar
- [x] The Call of the World-Shaman
- [x] The Nordrassil Summit #3572

All yours @rusher :)
