### ISSUE TITLE
[Quest] Twilight Highlands quest order (Alliance) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4462]
https://wowwiki.fandom.com/wiki/Twilight_Highlands_quests

- [x] Hero's Call: Twilight Highlands!
- [ ] My Son, the Prince #882
- [ ] Rallying the Fleet 
- [ ]  Twilight Investigation
- [x] Missing Parts #99
- [ ] The Usual Suspects #883 
- [ ] He's Holding Out on Us #3542
- [ ] Peasant Problems
- [ ] Unholy Cow
- [ ] Expert Opinion
- [ ] The Old Barracks
- [ ] Cataclysm in the Catacombs
- [ ] A Villain Unmasked
- [ ] Twilight Shores (from King Varian Wrynn)
- [ ] Twilight Shores (from Fargo Flintlocke)

### Opening the portals
_Opening the portal to Stormwind_

- [ ] Welcome to Highbank! 
- [x] Burnin' at Both Ends #4429 
- [ ] Aiming High #3432
- [ ] Kurdran's Waitin'
- [ ] Our Boys on the Shore
- [ ] Salvage Operation
- [ ] Naga Reinforcements
- [ ] Siren's Song
- [ ] Scouting the Shore 
- [ ] Landgrab
- [ ] Shredderectomy 
- [ ] Siege Tank Rescue
- [x] Bird Down! Bird Down! #3439 fixed
- [ ] Roots'll Do 'Er 
- [ ] Wings Over Highbank #3545
- [ ] The Perfect Poultice #3545 (quest order)
- [ ] Any Portal in a Storm
- [ ] The Way is Open

### Alliance progression
_Firebeard's Patrol (beginning)_

- [x] Firebeard's Patrol
- [ ] Welcome Relief 
- [x] The Only Homes We Have #3371
- [ ] Small Comforts
- [ ] Honorable Bearing
- [ ] Clan Mullan
- [ ] The Fighting Spirit
- [x] The Scent of Battle #283
- [ ] The Loyalty of Clan Mullan
- [ ] Stubborn as a Doyle
- [ ] The Fate of the Doyles
- [ ] Firebeard Bellows
- [ ] Death Worthy of a Dragonmaw
- [ ] Anything We Can Get
- [x] The Lost Brother #2674
- [ ] They Took Me Pants!
- [ ] Somethin' for the Boys
- [ ] Personal Request
- [ ] Dropping the Hammer #2637

### Dunwald Ruins

- [ ] Dunwalds Don't Die
- [ ] While Meeting The Family
- [x] Sifting Through The Wreckage  #3438
- [x] Donnelly Dunwald #652
- [ ] Finding Beak #4251
- [ ] Eoin Dunwald
- [x] Anything But Water #3433
- [ ] Cayden Dunwald
- [ ] Once More Into The Fire #2538
- [ ] Home Again
- [x] Doing It Like a Dunwald #2920

### Thundermar

- [ ] A Coward's Due
- [ ] Dragonmaw Takedown
- [ ] My Sister, Fanny
- [ ] Never Leave a Dinner Behind
- [ ] Fight Like a Wildhammer
- [ ] Magmalord Falthazar
- [x] A Vision of Twilight #3397
- [ ] We All Must Sacrifice 
- [ ] The Eyes Have It
- [x] Eye Spy #3397
- [ ] Tempered in Elemental Flame 
- [x] Hot Stuff #2214
- [ ] Potential Energy
- [x] Tear Them From the Sky! #3698
- [ ] Last Stand at Thundermar
- [x] Narkrall, The Drake-Tamer #3915

### Wildhammer Wedding (end of Alliance-only quests)

- [ ] The Kirthaven Summit
- [x] The Bachelor #622
- [x] Rescue at Glopgut's Hollow #622
- [x] Find Fanny #291
- [x] Ogre Bashin' #623
- [x] The Bachelorette #623
- [ ] Something Bold 
- [ ] Something Stewed
- [ ] Something Stolen
- [x] Words and Music By...#292
- [ ] Wild, Wild, Wildhammer Wedding #5235 (missing npc, no quest pickup)

### Neutral quest progression
_Iso'rath and the Earthen Ring_

- [ ] The Maw of Madness
- [ ] Torn Ground
- [ ] Pushing Back
- [ ] Simple Solutions
- [ ] Unbroken
- [ ] Mercy for the Bound
- [ ] The Maw of Iso'rath #1866
- [ ] Devoured
- [ ] The Worldbreaker
- [ ] The Terrors of Iso'rath
- [ ] Nightmare

### Vermillion Redoubt and the red dragonflight
After delivering #5338 the next quests npcs are not seen by players

- [ ] Warm Welcome https://www.wowhead.com/npc=48265/lauriel-trueblade `cant be seen by player`
- [ ] Even Dragons Bleed https://www.wowhead.com/npc=45528/calen `cant be seen by player`
- [ ] Draconic Mending https://www.wowhead.com/npc=45522/velastrasza  `cant be seen by player`
- [ ] Life from Death https://www.wowhead.com/npc=45562/baleflame  `cant be seen by player`
- [ ] In Defense of the Redoubt https://www.wowhead.com/npc=45522/velastrasza  `cant be seen by player`
- [ ] Encroaching Twilight https://www.wowhead.com/npc=45528/calen  `cant be seen by player`
- [ ] Breach in the Defenses https://www.wowhead.com/npc=45528/calen  `cant be seen by player`
- [ ] Far from the Nest https://www.wowhead.com/quest=27508/far-from-the-nest  `cant be seen by player`
- [ ] Mathias' Command https://www.wowhead.com/quest=28101/mathias-command  `cant be seen by player`
- [ ] Easy Pickings https://www.wowhead.com/quest=28103/easy-pickings
- [ ] If The Key Fits https://www.wowhead.com/npc=47592/master-mathias-shaw
- [ ] Paving the Way https://www.wowhead.com/npc=47611/highbank-lieutenant
- [ ] Pressing Forward https://www.wowhead.com/npc=47611/highbank-lieutenant
- [ ] Enter the Dragon Queen https://www.wowhead.com/npc=47603/alexstrasza-the-life-binder
- [ ] Battle of Life and Death https://www.wowhead.com/npc=49810/calen

### Final quests
_Twilight Gate_

- [x] Victors' Point #3440 #1895
- [ ] Ogres & Ettins
- [ ] Call in the Artillery #3289 
- [ ] SI:7 Drop #3543
- [ ] Kor'kron Drop #3291
- [ ] Move the Mountain #4127
- [x] Signal the Attack #2873 
- [x] Four Heads are Better than None #2164 
- [ ] Up to the Citadel #3293

### Twilight Citadel

- [ ] Just You and Mathias #4252
- [ ] Dark Assassins
- [ ] Bring the Hammer Down 
- [ ] Help from the Earthcaller
- [ ] Distract Them for Me #1868
- [ ] The Elementium Axe #1877
- [ ] Dragon, Unchained #1877
- [ ] Coup de Grace #4306

### Complete all of the following Elementium Depths quests (starts with Help from the Earthcaller above)

- [ ] Portal Overload #1880 
- [ ] Unbinding
- [ ] Spirit of the Loch
- [ ] Fire the Cannon #1878 
- [ ] Water of Life
- [ ] Mr. Goldmine's Wild Ride #4782
- [ ] A Little on the Side
- [ ] While We're Here 
- [ ] Rune Ruination
- [ ] A Fiery Reunion
- [x] Mathias Needs You #2206 
- [ ] The Hammer of Twilight #1879 
- [ ] Skullcrusher the Mountain
- [ ] Skullcrusher the Mountain  #3304

### Obsidian Forest and the red dragonflight

- [ ] And the Sky Streaked Red
- [ ] A Fitting End 
- [x] Shining Through the Dark #3434  
- [ ] Blackout
- [ ] Following the Young Home  #5022
- [ ] Last of Her Kind

### Crucible of Carnage  

#531

- [ ] The Crucible of Carnage: The Bloodeye Bruiser!
- [ ] The Crucible of Carnage: The Deadly Dragonmaw!
- [ ] The Crucible of Carnage: Calder's Creation!
- [ ] The Crucible of Carnage: The Earl of Evisceration!
- [ ] The Crucible of Carnage: The Twilight Terror!

**Comment by Constant20** [comment]
Find Fanny #291 fix confirmed in Dev
