### ISSUE TITLE
[Quest] Twilight Highlands quest order (Horde) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4463]
https://wowwiki.fandom.com/wiki/Twilight_Highlands_quests

- [x] Warchief's Command: Twilight Highlands!
- [x] Machines of War
- [ ]  Weapons of Mass Dysfunction #1141
- [ ]  Sauranok Will Point the Way #513  and #5226 (prequest issue)
- [ ] Unfamiliar Waters #513  #4558
- [ ] Where Is My Warfleet? #5227
- [ ] Ready the Ground Troops #2377
- [ ] Ready the Navy #5229
- [x] Beating the Market #2344
- [ ] Ready the Air Force #5228 
- [x] Smoot's Samophlange #2378 
- [x] Pre-Flight Checklist
- [ ] Twilight Skies (Captain Krazz) #5230
- [ ] Twilight Skies (Friz Groundspin) #4546   #4547   #4548   #5231

### Opening the portals
_Opening the portal to Orgrimmar_
**(when you follow the questline, this part has many phasing issues, because the portals to twilight are availible too early so players mess up their questline)** 

- [ ] Stalled Negotiations #4549
- [ ] Madness #4554
- [ ] Emergency Aid #4545
- [ ] Dangerous Compassion #4545 
- [ ] Negotiations Terminated
- [ ] You Say You Want a Revolution #4550 
- [ ] Insurrection #4551
- [ ] Death to Mor'ghor #4552
- [ ] Securing the Beach Head #4553
- [ ] Cementing Our Victory #4555 
- [ ] Muddied Waters 
- [ ] The Warchief Will be Pleased #4556 
- [ ] Traitor's Bait #4557
- [x] Return to the Highlands 

### Horde progression
_Highland Shores (beginning)_

- [x] The Southern Flank
- [x] Scouting the Shore
- [x] Blood on the Sand
- [ ] Mo' Better Shredder #517 (**phasing fixes when you hand this in**) 
- [x] The Northern Flank #3252
- [ ] Blood in the Surf
- [ ] Shells on the Sea Shore
- [ ] Blast Him!

### Krazzworks

- [x] Krazzworks
- [ ] Wildhammer Infestation #517
- [ ] Pool Pony Rescue  #1871
- [ ] Quality Construction #1870
- [x] Everything But the Kitchen Sink 
- [ ] Reprisal #3253 (**npc missing to hand back**)
- [ ] Off The Wall (**missing npc cant pick up quest**) #3253
- [ ] Parting Packages #4609
- [ ] Highbank, Crybank #3253
- [ ] Of Utmost Importance #3253 (**missing npc cant pick up quest**)
- [ ] Krazz Works! #3253 (**missing npc cant pick up quest**)

### The Gullet

- [ ] Purple is Your Color
- [ ] Dressed to Kill
- [ ] Whispers in the Wind
- [ ] Thog's Nightlight
- [x] Night Terrors #1869 (fixed)

### Bloodgulch (end of Horde-only quests)

- [x] Narkrall, the Drake-Tamer #1865
- [ ] Drag 'em Down #3229 #1864
- [ ] Crushing the Wildhammer
- [ ] War Forage
- [ ] Total War #1867
- [x]  A Vision of Twilight #3397
- [ ] We All Must Sacrifice
- [ ] The Eyes Have It
- [x] Eye Spy #3397
- [ ] Paint it Black
- [ ] Bait and Throttle
- [ ] How to Maim Your Dragon #3230
- [ ] The Demon Chain 
- [ ] Fury Unbound 

### Neutral quest progression
look here for neutral #4462
_Iso'rath and the Earthen Ring_

- [ ] The Weeping Wound

### Vermillion Redoubt and the red dragonflight

 - [ ] Warm Welcome https://www.wowhead.com/npc=48264/golluck-rockfist `cant be seen by player`
- [ ] Even Dragons Bleed https://www.wowhead.com/npc=45528/calen `cant be seen by player`
- [ ] Draconic Mending https://www.wowhead.com/npc=45522/velastrasza  `cant be seen by player`
- [ ] Life from Death https://www.wowhead.com/npc=45562/baleflame  `cant be seen by player`
- [ ] In Defense of the Redoubt https://www.wowhead.com/npc=45522/velastrasza  `cant be seen by player`
- [ ] Encroaching Twilight https://www.wowhead.com/npc=45528/calen  `cant be seen by player`
- [ ] Breach in the Defenses https://www.wowhead.com/npc=45528/calen  `cant be seen by player`
- [ ] Far from the Nest https://www.wowhead.com/quest=27508/far-from-the-nest  `cant be seen by player`
- [ ] Patchwork Command #4514
- [ ] The Gates of Grim Batol #4514
- [ ] Easy Pickings #4514
- [ ] Precious Goods #4514
- [ ] The Gates of Grim Batol https://www.wowhead.com/npc=47493/warlord-krogg `cant be seen by player`
- [ ] Paving the Way https://www.wowhead.com/npc=47374/patch `cant be seen by player`
- [ ] If The Key Fits https://www.wowhead.com/quest=28092/if-the-key-fits `cant be seen by player`
- [ ] Pressing Forward https://www.wowhead.com/quest=28093/pressing-forward `cant be seen by player`
- [ ] Enter the Dragon Queen https://www.wowhead.com/quest=28712/enter-the-dragon-queen `cant be seen by player`
- [ ] Battle of Life and Death https://www.wowhead.com/quest=28758/battle-of-life-and-death  `cant be seen by player`

### Final quests
_Twilight Gate_

- [x] Crushblow #1894
- [ ] Kor'kron Drop #3291
- [ ] Just You and Garona
- [ ] Garona Needs You

### Obsidian Forest and the red dragonflight
#4462

### Crucible of Carnage
#4462

**More info**
npc missing (Horde) 
https://cata.cavernoftime.com/npc=47492

**Quests** 
1. https://cata.cavernoftime.com/quest=28091
2. https://cata.cavernoftime.com/quest=27576
3. https://cata.cavernoftime.com/quest=28090
4. https://cata.cavernoftime.com/quest=28097
