### ISSUE TITLE
[Event] Brewfest - Horde test

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4620]
### Please spawn missing npcs first, then a retest can be made

**Links:**
https://wowpedia.fandom.com/wiki/Brewfest

**NPCs missing**
- [ ] _Orc Commoner_ http://cata.cavernoftime.com/npc=19175 (broken recently) possibly after same npc fix for midsummer
- [x] _Agnes Farwithers_ https://www.wowhead.com/npc=23604/agnes-farwithers
- [ ] _Bizzle Quicklift_ https://www.wowhead.com/npc=27216/bizzle-quicklift
- [ ] _Blood Elf Commoner_ https://www.wowhead.com/npc=19169/blood-elf-commoner (broken recently) possibly after same npc fix for midsummer
- [x]  _Bok Dropcertain_  https://www.wowhead.com/npc=24527/bok-dropcertain
- [ ] _Brew Vendor_ http://cata.cavernoftime.com/npc=27806       (#4624)
- [x] _Driz Tumblequick_  https://www.wowhead.com/npc=24510/driz-tumblequick
- [ ] _Drunken Brewfest Reveler_ http://cata.cavernoftime.com/npc=23698
- [ ] _Forsaken Commoner_ http://cata.cavernoftime.com/npc=19178 (broken recently) possibly after same npc fix for midsummer
- [ ] _Tauren Commoner_ http://cata.cavernoftime.com/npc=19176 (broken recently) possibly after same npc fix for midsummer
- [x] _Uta Roughdough_ https://www.wowhead.com/npc=23603/uta-roughdough
- [ ] _Vol'jin_ (during keg tapping ceremony)

![tapping of the keg](https://user-images.githubusercontent.com/39439201/88353931-9b575300-cd5f-11ea-91e4-7350ae645281.jpg)

**Quest line**

- [ ] Brewfest! (missing quest giver Orc Commoner_ http://cata.cavernoftime.com/npc=19175)
- [ ] Insult Coren Direbrew (Daily RDF) #4622
- [x] Direbrew's Dire Brew
- [ ] Chug and Chuck!
- [x] A New Supplier of Souvenirs
- [ ] This One Time, When I Was Drunk...
- [ ] Now This is Ram Racing... Almost.  #4626
- [ ] There and Back Again
- [ ] Bark for Drohn's Distillery!  / Bark for T'chali's Voodoo Brewery! (daily)
- [ ] Another Year, Another Souvenir 
- [ ] Brew of the Month Club
- [ ] Catch the Wild Wolpertinger!   #4623
- [ ] Pink Elekks On Parade #4625

**Achievements**
- [x] brew of the month https://www.wowhead.com/achievement=2796/brew-of-the-month (working when correct ID set for Blix) )
- [ ] brewmaster https://cata-twinhead.twinstar.cz/?achievement=1683
- [x] The Brewfest Diet https://cata-twinhead.twinstar.cz/?achievement=1185
- [x] direbrewfest https://www.wowhead.com/achievement=295/direbrewfest
- [ ] brew of the year https://www.wowhead.com/achievement=1183/brew-of-the-year
- [ ] disturbing the peace https://www.wowhead.com/achievement=293/disturbing-the-peace
- [x] Does Your Wolpertinger Linger? https://www.wowhead.com/achievement=1936/does-your-wolpertinger-linger
- [ ] Down With The Dark Iron https://cata-twinhead.twinstar.cz/?achievement=1186
- [ ] Drunken Stupor https://cata-twinhead.twinstar.cz/?achievement=1260
- [ ] Have Keg, Will Travel https://www.wowhead.com/achievement=303/have-keg-will-travel
- [x] Strange Brew https://www.wowhead.com/achievement=1203/strange-brew
- [ ] The Brewfest Diet https://www.wowhead.com/achievement=1185/the-brewfest-diet

**noted issues** 

- [ ] if player buys the Membership form from Blix Fixwidget quest ID item 37599, they cant deliver to Ray'ma, but if they buy the quest membership form ID 37737 from Ray'ma is works (wrong quest starter id on Blix Fixwidget) it should be  ID https://cata-twinhead.twinstar.cz/?npc=24495

**Comment by mfranca0009** [comment]
For some reason two NPC entries for brew vendor:
https://www.wowhead.com/npc=27817/brew-vendor
https://www.wowhead.com/npc=27819/brew-vendor

Not sure what this one is, since cavern of time says there is no known locations for this entry:
http://cata.cavernoftime.com/npc=27806

It seems maybe each entry sells different types of alcohol?

UPDATE -
https://i.gyazo.com/a1725a35f70ef7afeac11333fe273f76.png
Seems there are alot of NPC entries for this one type of NPC.

**Comment by Echinaceax** [comment]
_It seems maybe each entry sells different types of alcohol?_

Yes they is the spawned one in Org

**Comment by Echinaceax** [comment]
mfranca0009 says: _It seems maybe each entry sells different types of alcohol?_

yes, 27806 only sells 1 item https://www.wowhead.com/item=37488/wild-winter-pilsner

mfranca0009 says: _Not sure what this one is, since cavern of time says there is no known locations for this entry:_
http://cata.cavernoftime.com/npc=27806

its for this achievement  https://cata-twinhead.twinstar.cz/?item=37898#criteria-of but apparently doesnt exist now https://cata-twinhead.twinstar.cz/?achievement=346

more info 
https://www.wowhead.com/achievement=346/beverages-consumed
comments here https://www.wowhead.com/achievement=346/beverages-consumed#comments
i did search just the item it sells https://www.wowhead.com/item=37488/wild-winter-pilsner vendor only sells 1 item (in WOTLK)
no changes found from then until 4.1 it seems 

Patch 4.1 https://www.wowhead.com/news=185834/patch-4-1-ptr-build-13793-new-icons-items-and-spell-changes#news-post-185834 (we are at 4.0.3) atm

![citeria](https://user-images.githubusercontent.com/39439201/89121293-f4d92380-d4bd-11ea-8322-1ec45c643037.jpg)
