### ISSUE TITLE
[Quest] Uldum quest order 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4711]
- [x] Warchief's Command: Uldum! https://github.com/WoWManiaUK/Blackwing-Lair/issues/229
- [ ] Easy money https://github.com/WoWManiaUK/Blackwing-Lair/issues/1073
- [ ] Traitors https://github.com/WoWManiaUK/Blackwing-Lair/issues/1908
- [ ] Smoke in their Eyes https://github.com/WoWManiaUK/Blackwing-Lair/issues/3538
- [x] Budd's Plan 
- [x] Kavem the Callous https://github.com/WoWManiaUK/Blackwing-Lair/issues/3537
- [ ] Escape From the Lost City https://github.com/WoWManiaUK/Blackwing-Lair/issues/1909
- [ ] Impending Retribution https://github.com/WoWManiaUK/Blackwing-Lair/issues/2001
- [x] Al'Akir's Vengeance 
- [x] Under the Choking Sands (fixed)
- [x] Minions of Al'Akir
- [x] The Prophet Hadassi
- [x] The Prophet's Dying Words
- [x] Colossal Guardians (fixed)
- [x] The Scepter of Orsis 
- [x] Send Word to Phaoris
- [ ] The High Commander's Vote #5225 (quest giver missing) breaking quest series order
- [x] The Weakest Link
- [ ] Shaping Up https://github.com/WoWManiaUK/Blackwing-Lair/issues/2198
- [ ] Salhet's Secret https://github.com/WoWManiaUK/Blackwing-Lair/issues/2198#issuecomment-841893925
- [ ] Salhet the Tactician https://github.com/WoWManiaUK/Blackwing-Lair/issues/2198#issuecomment-841893925
- [ ] Return to Camp https://github.com/WoWManiaUK/Blackwing-Lair/issues/2198#issuecomment-841893925
- [ ] The High Priest's Vote #5225  (quest giver missing)
- [ ] Trespassers in the Water
- [ ] Stopping the Spread
- [ ] The Defilers' Ritual #3076
- [x] The Root of the Corruption
- [x] The Vizier's Vote #5225 (quest giver missing)
- [x] Tanotep's Son
- [x] Neferset Prison
- [x] The Pit of Scales
- [x] The High Council's Decision
- [x] Nahom Must Hold
- [x] The Secret of Nahom
- [x] Punish the Trespassers
- [x] The Cypher of Keset
- [x] The Defense of Nahom
- [x] The Curse of the Tombs
- [x] Artificial Intelligence
- [ ] A Disarming Distraction https://github.com/WoWManiaUK/Blackwing-Lair/issues/4296
- [x] Core Access Codes
- [ ] Hacking the Wibson https://github.com/WoWManiaUK/Blackwing-Lair/issues/1906
- [ ] Gnomebliteration https://github.com/WoWManiaUK/Blackwing-Lair/issues/4296
- [x] The Push Westward
- [x] Lieutenants of Darkness
- [x] Bleeding the Enemy
- [x] Salhet's Gambit
- [x] The Fall of Neferset City
- [ ] Premature Explosionation #5077
- [ ] Field Work https://github.com/WoWManiaUK/Blackwing-Lair/issues/3093
- [x] Just the Tip https://github.com/WoWManiaUK/Blackwing-Lair/issues/3244
- [ ] On to Something #5248
- [ ] The Thrill of Discovery
- [x] Be Prepared (fixed)
- [x] Lessons From the Past (fixed)
- [x] Be Prepared (fixed)
- [ ] By the Light of the Stars https://github.com/WoWManiaUK/Blackwing-Lair/issues/3075
- [ ] Tipping the Balance https://github.com/WoWManiaUK/Blackwing-Lair/issues/3074  and https://github.com/WoWManiaUK/Blackwing-Lair/issues/3244
- [x] After the Fall
- [x] Just a Fancy Cockroach
- [ ] Do the Honors https://github.com/WoWManiaUK/Blackwing-Lair/issues/3092
- [x] I've Got This Guy
- [x] They Don't Know What They've Got Here (fixed)
- [ ] Ignition https://github.com/WoWManiaUK/Blackwing-Lair/issues/2163
- [ ] Tailgunner! https://github.com/WoWManiaUK/Blackwing-Lair/issues/2165
- [ ] Eastern Hospitality https://github.com/WoWManiaUK/Blackwing-Lair/issues/2196
- [x] A Favor for the Furrier
- [ ] The Desert Fox https://github.com/WoWManiaUK/Blackwing-Lair/issues/4117
- [x] Fashionism (fixed)
- [x] Idolatry (fixed)
- [x] Angered Spirits
- [x] Gobbles!
- [ ] Make Yourself Useful https://github.com/WoWManiaUK/Blackwing-Lair/issues/4118
- [ ] Crisis Management https://github.com/WoWManiaUK/Blackwing-Lair/issues/268
- [ ] Battlezone #4774 
- [ ] Missed Me By Zhat Much! due to this  #4774 quest cant be picked up
- [ ] Lockdown! 
- [ ] The Great Escape
- [ ] Sending a Message 
- [ ] Firing Squad 
- [x] Meet Me In Vir'sar
- [x] Friend of a Friend
- [x] Two Tents
- [x] Master Trapper
- [x] Unlimited Potential
- [x] Camel Tow
- [x] Reduced Productivity
- [x] Missing Pieces
- [x] Stirred the Hornet's Nest
- [x] Myzerian's Head
- [x] Shroud of the Makers
- [x] Schnottz So Fast
- [x] Bad Datas
- [x] I'll Do It By Hand
- [x] Sullah's Gift https://github.com/WoWManiaUK/Blackwing-Lair/issues/4703
- [x] Fire From the Sky https://github.com/WoWManiaUK/Blackwing-Lair/issues/4704
- [x] See You on the Other Side! https://github.com/WoWManiaUK/Blackwing-Lair/issues/4706
- [x] Fortune and Glory https://github.com/WoWManiaUK/Blackwing-Lair/issues/4706
- [x] Harrison Jones and the Temple of Uldum https://github.com/WoWManiaUK/Blackwing-Lair/issues/4707
- [x] Put That Baby in the Cradle! https://github.com/WoWManiaUK/Blackwing-Lair/issues/4707
- [x] Three if by Air https://github.com/WoWManiaUK/Blackwing-Lair/issues/4708
- [x] The Coffer of Promise https://github.com/WoWManiaUK/Blackwing-Lair/issues/4705
- [x] The Heart of the Matter https://github.com/WoWManiaUK/Blackwing-Lair/issues/2359
- [x] Penetrating Their Defenses https://github.com/WoWManiaUK/Blackwing-Lair/issues/2359
- [ ] Doing it the Hard Way https://github.com/WoWManiaUK/Blackwing-Lair/issues/4709
