### ISSUE TITLE
[Questline] Northern Stranglethorn storyline (horde) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4822]
**Links:**
https://wow.gamepedia.com/Northern_Stranglethorn_storyline

- [x] Warchief's Command: Northern Stranglethorn!  #4824
- [x] The Defense of Grom'gol: Raptor Risk
- [x] The Defense of Grom'gol: Ogre Oppression 
- [x] The Defense of Grom'gol: Murloc Menace
- [x] The Defense of Grom'gol: Trollish Thievery
- [x] A Lashtail Hatchling
- [x] I Think She's Hungry
- [x] Favored Skull
- [ ] A Nose for This Sort of Thing #4416
- [ ] Who's a Big Troll? #4825
- [ ] Skullsplitter Mojo  #4826
- [x] Bloodlord Mandokir (npc missing) https://github.com/WoWManiaUK/Blackwing-Lair/issues/4827
- [x] Priestess Hu'rala
- [x] Mind Vision
- [ ] See Raptor #4417 
- [x] Mind Control
- [ ] Be Raptor #4829
- [x] Surkhan (cant pick up due to missing last quest complete) after quest completed myself with command was done
- [x] Population Con-Troll
- [x] Bloodscalp Insight
- [x] An Unusual Patron
- [x] Hunt for Yenniku
- [x] Headhunting
- [x] Nezzliok Will Know
- [x] Speaking with Nezzliok
- [x] Chasing Yenniku's Fate
- [x] The Mind's Eye
- [ ] Saving Yenniku #4473
- [x] Cozzle's Plan
- [x] Nighttime in the Jungle
- [x] Zul'Mamwe Mambo
- [x] The Mosh'Ogg Bounty
- [ ] The Universal Key #4830
- [x] Venture Company Mining
- [x] Above My Pay Grade
