### ISSUE TITLE
[Questline] Northern Stranglethorn storyline (Ally) 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4823]
**Links:**

https://wow.gamepedia.com/Northern_Stranglethorn_storyline

- [x] Hero's Call: Northern Stranglethorn Vale!
- [x] The Fate of Kurzen
- [x] Bad Medicine
- [x] Just hatched
- [x]  Spared from Madness
- [x] Control Sample
- [ ] I Think She's Hungry #4846
- [x] Stopping Kurzen's Legacy
- [x] The Source of the Madness
- [x]  Krazek's Cookery
- [x] Venture Company Mining
- [x] Return to Corporal Kaleb
- [x] Favored Skull
- [ ] A Nose for This Sort of Thing #4416
- [ ] A Physical Specimen #4847  (same issue for horde, different quest name tho #4825) 
- [ ] Bloodlord Mandokir
- [x] Priestess Thaalia
- [x] Mind Vision
- [ ] See Raptor #4417
- [x] Mind Control
- [ ] Be Raptor #4829
- [x] Ghaliri
- [ ] An Old Friend #4848
- [x] Bloodscalp Insight
- [x] Deep Roots
- [x] Sacred to the Bloodscalp
- [x] Population Con-Troll
- [x] You Can Take the Murloc Out of the Ocean...
- [x] The Altar of Naias
- [x] Zul'Mamwe Mambo
- [x] Nighttime in The Jungle
- [x] The Mosh'Ogg Bounty
- [x] To the Cape! 
- [x] Tiger Hunting
- [x] Tiger Stalking
- [x] Tiger Prowess
- [x] Tiger Mastery
- [x] Panther Hunting
- [x] Panther Stalking
- [x] Panther Prowess
- [x] Panther Mastery
- [x] Raptor Hunting
- [x] Raptor Stalking
- [x] Raptor Prowess
- [x] Raptor Mastery
- [x] Big Game Hunter
- [ ] Welcome to the Jungle
- [x] Supply and Demand
- [x] Some Assembly Required
- [x] Excelsior
- [x] The Green Hills of Stranglethorn
