### ISSUE TITLE
[Quest/order] Full Quest order - Deepholm 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4905]
**Links:**

https://wowwiki.fandom.com/wiki/Quest:The_Stone_Throne

Upper World Pillar Fragment
From the Eastern Earthshrine in Stormwind / the Western Earthshrine in Orgrimmar:

- [x] Hero's Call: Deepholm! / H [82] Warchief's Command: Deepholm! (optional)
- [x] The Maelstrom
- [x] Deepholm, Realm of Earth
Complete all of:
- [x] Gunship Down & N [82] Captain's Log  #2915  
- [x] Elemental Energy #3041
- [x] The Earth Claims All 
- [x] Diplomacy First
Complete all of:
- [x] All Our Friends Are Dead #2624
- [x] The Admiral's Cabin & N [82] Without a Captain or Crew #4179
- [x] Take No Prisoners / N [82] On Second Thought, Take One Prisoner #4178
- [x] Some Spraining to Do #2625
- [x] Return to the Temple of Earth
- [x] Deathwing's Fall #4043
Side quest: N [82] Blood of the Earthwarder #1783
- [x] Bleed the Bloodshaper
- [x] Question the Slaves #3154
- [ ] The Forgemaster's Log #3155
- [x] Silvermarsh Rendezvous #4044
- [x] Quicksilver Submersion
Side chain: N [82] Twilight Research, N [82] Maziel's Revelation‎, N [82] Maziel's Ascendancy
- [x] The Twilight Overlook
- [x] Big Game, Big Bait / N [82] To Catch a Dragon #1990
- [ ] Testing the Trap #2771
- [x] Abyssion's Minions / N [82] Block the Gates
- [x] The World Pillar Fragment

**To Where's Goldmine?**

Middle World Pillar Fragment
- [x] Where's Goldmine?
- [x] Explosive Bonding Compound
- [x] Something that Burns #797
- [x] Apply and Flash Dry
- [ ] Take Him to the Earthcaller #2954
- [x] To Stonehearth's Aid
Complete all of:
- [x] The Quaking Fields
- [ ] The Axe of Earthly Sundering / N [82] Elemental Ore  #1991
- [ ] One With the Ground #2961
- [x] Bring Down the Avalanche #3329
- [ ] Stonefather's Boon & N [82] Sealing the Way #3020 and #3022
- [ ] We're Surrounded & N [82] Thunder Stones
- [ ] Shatter Them! / N [82] Battlefront Triage / N [82] Fixer Upper #1800 and #2741
- [x] Troggzor the Earthinator #3527
- [x] Rush Delivery
- [ ] Close Escort #1992
- [ ] Keep Them off the Front #2962
- [ ] Reactivate the Constructs / N [83] Mystic Masters #2963 and #2965
- [x] Down Into the Chasm
- [ ] Sprout No More / N [83] Fungal Monstrosities #1994 for both
- [x] A Slight Problem
- [ ] Rescue the Stonefather... and Flint #3153
- [x] The Hero Returns
- [x] The Middle Fragment

To The Very Earth Beneath Our Feet.

**Lower World Pillar Fragment**
- [ ] The Very Earth Beneath Our Feet #4515 also this help to fix rep issue https://github.com/WoWManiaUK/Blackwing-Lair/issues/4891#issuecomment-729948597
- [x] Crumbling Defenses / N [83] On Even Ground / N [83] Core of Our Troubles #3729 #3728 
- [ ] Imposing Confrontation #4892
- [x] Rocky Relations
- [x] Hatred Runs Deep / N [83] Unsolid Ground / N [83] Loose Stones #3732 and #3731
- [ ] Violent Gale #4518
- [x] Depth of the Depths
- [ ] A Rock Amongst Many #4893
- [ ] Entrenched #4900
- [ ] Intervention / N [83] Making Things Crystal Clear / N [83] Putting the Pieces Together #4900 #3006
- [ ] Clingy #3760
- [x] So Big, So Round...
- [x] Rock Bottom
- [x] Petrified Delicacies #3759
- [x] Steady Hand
- [x] Don't. Stop. Moving #3060
- [x] Hard Falls / N [83] Fragile Values
- [x] Resonating Blow #2948
- [x] Rocky Upheaval
Complete all of:
- [x] Doomshrooms / N [83] Gone Soft
- [ ] Familiar Intruders & N [83] A Head Full of Wind & N [83] Unnatural Causes  #3004  
- [ ] Shaken and Stirred / N [83] Corruption Destruction / N [83] Wrath of the Fungalmancer #4901  for all three
- [x] At the Stonemother's Call #2757
- [ ] Audience with the Stonemother #2826
- [ ] Rallying the Earthen Ring #3221
- [x] Our Part of the Bargain #3222
- [ ] The Stone March / N [83] Therazane's Mercy / N [83] The Twilight Flight #3223 and #4903 
- [x] Word In Stone
- [ ] Undying Twilight #4295
- [ ] The Binding #4297
- [ ] The Stone Throne #4904
