### ISSUE TITLE
[Questline] Azshara storyline (horde)

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5039]
**Links:**

https://wow.gamepedia.com/Azshara_storyline

- [x]  Warchief's Command: Azshara! #5040 (fix 1st) 
- [x]  Beyond Durotar (closes 2 quest below) correct if you do the questline from the warboard/ a goblin
- [x]  Report to the Labor Captain (goblin only)
- [ ]  Runaway Shredder! #5041
- [ ] The Captain's Logs  #5044
- [ ] Up a Tree  #5046
- [ ] Defend the Gates!  #5042 
- [ ] Arborcide  #5043
- [x] The Eyes of Ashenvale (fixed) #1151
- [x] Venison for the Troops (fixed) but this the fix bugged the quest #1154
- [x] Return of the Highborne?
- [x] Report to Horzak
- [x] Basilisk Bashin'
- [x] A Quota to Meet
- [ ] Stone Cold #4154
- [x] The Perfect Prism
- [x] Prismbreak
- [x] Refleshification  (fixed) #967
- [x] Another Warm Body
- [x] Hand-me-downs (fixed) #980
- [x] Military Breakthrough
- [ ] First Degree Mortar #4155 
- [ ] In The Face! #982
- [x] Profitability Scouting
- [x] Private Chat
- [ ] Survey the Lakeshore #4157 
- [x] A Thousand Stories in the Sand
- [x] Memories of the Dead #968
- [ ] Mystery of the Sarcen Stone
- [x] Gunk in the Trunk (fixed) #4182 
- [ ] Dozercism #4534 
- [x] Need More Science
- [x] When Science Attacks #969 
- [ ] Bad Science! Bad!
- [x] My Favorite Subject (fixed) #979 
- [x] Nine's Plan (fixed) #1614
- [ ] Raptor Raptor Rocket #4181
- [ ] Segmentation Fault: Core Dumped #4535
- [x] Mysterious Azsharite (fixed) #970
- [ ] A Gigantic Snack
- [x] Befriending Giants (fixed) #971
- [ ] Azsharite Experiment Number One #4191
- [x] The Terrible Tinkers of the Ruined Reaches #972 
- [ ] Azsharite Experiment Number Two  #4544
- [ ] A Hello to Arms
- [ ] Mortar the Point
- [ ] Investigating the Sea Shrine
- [ ] To Gut a Fish
- [ ] The Keystone Shard 
- [ ] Report to Twocrush 
- [ ] Sisters of the Sea #4193 
- [ ] Azshara Blues 
- [ ] Friends Come In All Colors 
- [ ] That's Just Rude! 
- [ ] A Little Pick-me-up
- [x] Absorbent (fixed) #976
- [ ] Full of Hot Water 
- [ ] Wash Out #977
- [ ] Dressed to Impress
- [ ] Renewable Resource
- [ ] Shear Will 
- [ ] Waste of Thyme
- [ ] Trouble Under Foot #5035
- [ ] Manual Labor 
- [x] The Pinnacle of Learning #5037 
- [ ] Watch Your Step #5038 (and missing npc) 

missing npc, GM helped with quest
- [ ] The Trial of Fire
- [ ] The Trial of Frost 
- [ ] The Trial of Shadow
- [ ] Xylem's Asylum 
- [ ] Wasn't It Obvious? 
- [ ] Easy is Boring 
- [ ] Turning the Tables 
- [ ] Fade to Black #975
- [ ] Ice Cold #4154
- [ ] Pro-liberation #997
- [ ] Farewell, Minnow 
- [ ] Amberwind's Journal 
- [ ] Arcane De-Construction
- [ ] Hacking the Construct
- [ ] The Blackmaw Scar
- [ ] A Pale Brew
- [x] Diplomacy by Another Means (fixed) #1633 
- [x] The Blackmaw Doublecross (fixed) #978
- [ ] Operation Fishgut
- [ ] Rapid Deployment
- [ ] There Are Many Like It
- [ ] First Come, First Served
- [ ] Halo Drops
- [ ] Mop Up
- [ ] Field Promotion
- [ ] Extermination
- [ ] Handling the Goods #1156
- [ ] Head of the Snake #984
- [ ] Still Beating Heart 
- [ ] Ticker Required #985 
- [ ] Shore Leave
- [x] Airborne Again #973
- [ ] Let Them Feast on Fear
- [ ] Commando Drop
- [ ] Where's My Head?
- [ ] Lightning Strike Assassination
- [ ]  Grounded! #996
- [ ] Rigged to Blow
- [ ] Push the Button!
- [ ] Blacken the Skies #995
- [ ] The Conquest of Azshara
- [ ] Probing into Ashenvale
