### ISSUE TITLE
[Event] Children's Week - full report 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5088]
**Links:**
https://wow.gamepedia.com/Children%27s_Week
https://cata-twinhead.twinstar.cz/?event=201
https://cata-twinhead.twinstar.cz/?search=Orphan

**NPCs missing** **[ALL FIXED]**

- [x] Arch Druid Hamuul Runetotem https://cata-twinhead.twinstar.cz/?npc=52729
- [x] Kador Cloudsong https://cata-twinhead.twinstar.cz/?npc=52787
- [x] Baine Bloodhoof https://cata-twinhead.twinstar.cz/?npc=52700
- [x] Snixx Quickfreeze https://cata-twinhead.twinstar.cz/?npc=52818
- [x] Crusty Bob https://cata-twinhead.twinstar.cz/?npc=21376
- [x] Rental Chopper https://cata-twinhead.twinstar.cz/?npc=52189
- [x] Cone of Cold Shop Circle https://cata-twinhead.twinstar.cz/?npc=52412
- [x] Redhound Two-Seater https://cata-twinhead.twinstar.cz/?npc=52585
- [x] Orphan Matron Nightingale https://cata-twinhead.twinstar.cz/?npc=51988
- [x] Hans Coldhearth https://cata-twinhead.twinstar.cz/?npc=52421
- [x] Bazzil Frostweaver https://cata-twinhead.twinstar.cz/?npc=52420
- [x] Apprentice Mage https://cata-twinhead.twinstar.cz/?npc=52423
- [x] Emmithue Smails https://cata-twinhead.twinstar.cz/?npc=14481

**NPC issues** **[ALL FIXED]**
- [x] Snixx Quickfreeze https://cata-twinhead.twinstar.cz/?npc=52818
- [x] Orphan Matron Battlewail #1406 

**Objects missing** **[ALL FIXED]**
- [x] Cairne Offering 1 https://cata-twinhead.twinstar.cz/?object=208433
- [x] Cairne Offering 2 https://cata-twinhead.twinstar.cz/?object=208434
- [x] Ice Cream https://cata-twinhead.twinstar.cz/?object=208567
- [x] Ice Cream https://cata-twinhead.twinstar.cz/?object=208565
- [x] Ice Cream https://cata-twinhead.twinstar.cz/?object=208566
- [x] Ice Cream https://cata-twinhead.twinstar.cz/?object=208564
- [x] Ice Cream Cone https://cata-twinhead.twinstar.cz/?object=208385
- [x] Ice Cream Shop Ice https://cata-twinhead.twinstar.cz/?object=208379
- [x] Ice Cream Stand Counter https://cata-twinhead.twinstar.cz/?object=208377
- [x] Ice Cream Stand Crate https://cata-twinhead.twinstar.cz/?object=208378
- [x] Ice Cream Store Fruit Bucket https://cata-twinhead.twinstar.cz/?object=208383
- [x] The Cone of Cold https://cata-twinhead.twinstar.cz/?object=208384 

**Quests not working**
- [ ] Ridin' the Rocketway https://cata-twinhead.twinstar.cz/?quest=29146 reported here #5094
- [ ] Cruisin' the Chasm https://www.wowhead.com/quest=29093/cruisin-the-chasm reported #5103

 **Achievements**
- [x] Aw, Isn't It Cute? https://www.wowhead.com/achievement=1792/aw-isnt-it-cute
- [x] Home Alone https://cata-twinhead.twinstar.cz/?achievement=1791
- [x] Hail To The King, Baby https://cata-twinhead.twinstar.cz/?achievement=1790
- [x] Veteran Nanny https://cata-twinhead.twinstar.cz/?achievement=275
- [x] Bad Example https://cata-twinhead.twinstar.cz/?achievement=1788
- [x] Daily Chores https://cata-twinhead.twinstar.cz/?achievement=1789

### tested working

Wolvar Orphan 

- [x] Little Orphan Kekek Of The Wolvar https://www.wowhead.com/quest=13927/little-orphan-kekek-of-the-wolvar
- [x] Home Of The Bear-Men https://www.wowhead.com/quest=13930/home-of-the-bear-men
- [x] The Dragon Queen https://www.wowhead.com/quest=13955/the-dragon-queen
- [x] The Mighty Hemet Nesingwary https://www.wowhead.com/quest=13957/the-mighty-hemet-nesingwary
- [x] Playmates https://www.wowhead.com/quest=13951/playmates
- [x] The Bronze Dragonshrine https://www.wowhead.com/quest=13933/the-bronze-dragonshrine
- [x] A Visit To The Wonderworks https://www.wowhead.com/quest=13938/a-visit-to-the-wonderworks
- [x] Back To The Orphanage https://www.wowhead.com/quest=13960/back-to-the-orphanage

Human Orphan 

- [x] Children's Week https://www.wowhead.com/quest=1468/childrens-week
- [x] Malfurion Has Returned! https://www.wowhead.com/quest=29107/malfurion-has-returned  reported #5104
- [x] The Biggest Diamond Ever! https://www.wowhead.com/quest=29106/the-biggest-diamond-ever reported here #5097
- [x] Let's Go Fly a Kite https://www.wowhead.com/quest=29117/lets-go-fly-a-kite reported here #5098 
- [x] You Scream, I Scream...https://classic.wowhead.com/quest=4822/you-scream-i-scream
- [x] A Warden of the Alliance https://classic.wowhead.com/quest=171/a-warden-of-the-alliance reported #5106

Bloodelf orphan

- [x] Children's Week 
- [x] Visit the Throne of the Elements https://www.wowhead.com/quest=10953/visit-the-throne-of-the-elements
- [x] Hch'uu and the Mushroom People https://www.wowhead.com/quest=10945/hchuu-and-the-mushroom-people
- [x] A Trip to the Dark Portal https://www.wowhead.com/quest=10951/a-trip-to-the-dark-portal
- [x] Now, When I Grow Up... https://www.wowhead.com/quest=11975/now-when-i-grow-up
- [x] Time to Visit the Caverns https://www.wowhead.com/quest=10963/time-to-visit-the-caverns
- [x] Back to the Orphanage https://www.wowhead.com/quest=10967/back-to-the-orphanage

Draenei Orphan 

- [x] Children's week https://www.wowhead.com/quest=10943/childrens-week
- [x] A Trip to the Dark Portal https://www.wowhead.com/quest=10952/a-trip-to-the-dark-portal 
- [x] Auchindoun and the Ring of Observance https://www.wowhead.com/quest=10950/auchindoun-and-the-ring-of-observance
- [x] Jheel is at Aeris Landing! https://www.wowhead.com/quest=10954/jheel-is-at-aeris-landing
- [x] The Seat of the Naaru https://www.wowhead.com/quest=10956/the-seat-of-the-naaru
- [x] Call on the Farseer https://www.wowhead.com/quest=10968/call-on-the-farseer
- [x] Time to Visit the Caverns https://www.wowhead.com/quest=10962/time-to-visit-the-caverns
- [x] Back to the Orphanage https://www.wowhead.com/quest=10966/back-to-the-orphanage

Orcish Orphan 

- [x] Children's week https://www.wowhead.com/quest=172/childrens-week 
- [x] Let's Go Fly a Kite https://cata-twinhead.twinstar.cz/?quest=29190 
- [x] The Banshee Queen https://cata-twinhead.twinstar.cz/?quest=29167   reported here #5095
- [x] A Warden of the Horde https://cata-twinhead.twinstar.cz/?quest=5502 reported #5105
- [x] You Scream, I Scream... https://cata-twinhead.twinstar.cz/?quest=29191
- [x] The Fallen Chieftain https://cata-twinhead.twinstar.cz/?quest=29176 reported here #5096

Blood Elf Orphan 

- [x] Orcish Orphan https://cata-twinhead.twinstar.cz/?npc=14444 (missing quests) Orphan Matron Battlewail #1406 (fixed)
- [x] Children's Week https://cata-twinhead.twinstar.cz/?quest=10942
- [x] A Trip to the Dark Portal https://cata-twinhead.twinstar.cz/?quest=10951   #1403 
- [x] Hch'uu and the Mushroom People https://cata-twinhead.twinstar.cz/?quest=10945  #1403 
- [x] When I Grow Up... https://cata-twinhead.twinstar.cz/?quest=10960
- [x] Time to Visit the Caverns https://cata-twinhead.twinstar.cz/?quest=10963
- [x] Now, When I Grow Up... https://cata-twinhead.twinstar.cz/?quest=11975
- [x] Back to the Orphanage https://cata-twinhead.twinstar.cz/?quest=10967 

Oracle Orphan 

- [x] Back To The Orphanage  https://cata-twinhead.twinstar.cz/?quest=22879  
- [x] Little Orphan Roo Of The Oracles https://www.wowhead.com/quest=13926/little-orphan-roo-of-the-oracles
- [x] The Biggest Tree Ever! https://www.wowhead.com/quest=13929/the-biggest-tree-ever
- [x] Meeting a Great One https://www.wowhead.com/quest=13956/meeting-a-great-one
- [x] Playmates! https://www.wowhead.com/quest=13950/playmates
- [x] The Bronze Dragonshrine https://www.wowhead.com/quest=13933/the-bronze-dragonshrine
- [x] The Dragon Queen https://www.wowhead.com/quest=13955/the-dragon-queen
- [x] A Trip To The Wonderworks https://www.wowhead.com/quest=13937/a-trip-to-the-wonderworks
- [x] Back To The Orphanage https://cata-twinhead.twinstar.cz/?quest=13959 

### NOT FINISHED need testing 

- [ ] School of Hard Knocks https://cata-twinhead.twinstar.cz/?achievement=1786

![image](https://user-images.githubusercontent.com/39439201/109330335-dbce0080-785b-11eb-9c08-991ff5d281a6.png)

**Comment by Echinaceax** [comment]
### added info 
https://cata-twinhead.twinstar.cz/?issue=14752

https://www.wowhead.com/quest=29093/cruisin-the-chasm

_Quest Cruisin 'the Chasm For players with an open final phase in Sentinel Hill (after completing the q line), NPCs are not available at this stage exactly according to the original bug description in # CATACLYSM-10835: Quest - Cruisin' the Chasm (Fixed). Q cannot be completed in a party with a player who does not have SH phased. NPC Orphan Matron Nightingale After receiving q Children's Week for the first time, he gives the player a Human Orphan Whistle to summon an orphan who offers 3 parallel quests in the first place (1) (see above), 2), 3)). If a player cancels one of the quests (in the case of the first bug, quite the expected procedure), the whistle to summon the orphan will disappear from his backpack, and a new one cannot be obtained from **Orphan Matron Nightingale even after clicking on the gossip "I need a new Human Orphan Whistle"**. I assume that after completing all the quests from the orphan, a new whistle from the matron can be obtained._


update
Sorted this part now

**Comment by mfranca0009** [comment]
NPC triggers don't have to be added in-game, they are only used for scripting purposes in C++ for quest credit, achievement credit, etc.

**Comment by Echinaceax** [comment]
closing this now, 99.8% done
