### ISSUE TITLE
[Event] Main report - Hallows End

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5114]
**Links:**
https://wow.gamepedia.com/Hallow%27s_End
https://wowwiki-archive.fandom.com/wiki/Hallow%27s_End

**Missing NPCs**
- [ ] Human Commoner https://www.wowhead.com/npc=18927/human-commoner
- [ ] Orc Commoner https://www.wowhead.com/npc=19175/orc-commoner
- [ ] Gretchen Fenlow https://www.wowhead.com/npc=51934/gretchen-fenlow
- [ ] Costumed Orphan Matron https://www.wowhead.com/npc=24519/costumed-orphan-matron
- [ ] Chub https://cata-twinhead.twinstar.cz/?npc=53757
- [ ] Celestine of the Harvest https://www.wowhead.com/npc=51665/celestine-of-the-harvest
- [ ] Masked Orphan Matron https://www.wowhead.com/npc=23973/masked-orphan-matron

**Missing Objects**

**Achievements**

**Quests bugged**
- [ ] Fire Brigade Practice #1557
- [ ] A Time to Build Up #1453
- [ ] Stink Bombs Away #1452
- [ ] Let the Fires Come! #1439
- [ ] Stop the Fires! #1428
- [ ] The Headless Horseman Pumpkin Shrine #4785

**Item issues**
- [x] Tooth Pick https://www.wowhead.com/item=37604/tooth-pick#contained-in-item  (to high %)  #4764
- [ ] Bobbing Apple #1425
- [x] candy buckets missing #4748 #4749 #4753 #4753 #4751 #4750 all missing

**NPCs dialog missing**
- [ ] Innkeeper Lyshaerya https://www.wowhead.com/npc=11103/innkeeper-lyshaerya
- [ ] Innkeeper Kyteran https://www.wowhead.com/npc=43420/innkeeper-kyteran

### NOT FINISHED YET 

**NEEDS CHECKING** 

- [ ] Darkcaller Yanka https://www.wowhead.com/npc=15197/darkcaller-yanka
- [ ] Edgar Goodwin https://cata-twinhead.twinstar.cz/?npc=54141
- [ ] Jesper https://www.wowhead.com/npc=15310/jesper
- [ ] Gretchen Fenlow https://www.wowhead.com/npc=51934/gretchen-fenlow
- [ ] Keira https://www.wowhead.com/npc=52064/keira
- [ ] Candace Fenlow https://www.wowhead.com/npc=53763/candace-fenlow
- [ ] Hired Courier https://cata-twinhead.twinstar.cz/?npc=53950
- [ ] Auctioneer Drezmit https://cata-twinhead.twinstar.cz/?npc=44866
- [ ] Delian Sunshade https://cata-twinhead.twinstar.cz/?npc=54146
- [ ] Spoops https://www.wowhead.com/npc=15309/spoops
- [ ] Darla https://cata-twinhead.twinstar.cz/?npc=53756
- [ ] Farina https://cata-twinhead.twinstar.cz/?npc=53760
- [ ] Crina Fenlow https://cata-twinhead.twinstar.cz/?npc=53764
- [ ] Dran Droffers https://cata-twinhead.twinstar.cz/?npc=6986  
- [ ] Maxim the Sly https://cata-twinhead.twinstar.cz/?npc=54169
- [ ] Orphan Matron Nanee https://cata-twinhead.twinstar.cz/?npc=53865
- [ ] Anson Hastings https://cata-twinhead.twinstar.cz/?npc=53949
- [ ] Hired Courier https://cata-twinhead.twinstar.cz/?npc=54142
- [ ] Auctioneer Fitch https://cata-twinhead.twinstar.cz/?npc=8719
- [ ] Hudson Barnes https://cata-twinhead.twinstar.cz/?npc=54021
- [ ] Hudson Barnes https://cata-twinhead.twinstar.cz/?npc=54118
- [ ] Stymie https://cata-twinhead.twinstar.cz/?npc=53702
- [ ] Spanky https://cata-twinhead.twinstar.cz/?npc=52497
- [ ] Dorothy https://cata-twinhead.twinstar.cz/?npc=53728
- [ ] Gertrude Fenlow https://cata-twinhead.twinstar.cz/?npc=52548
- [ ] Quincy Cutler https://cata-twinhead.twinstar.cz/?npc=53991
- [ ] Ren Quickhand https://cata-twinhead.twinstar.cz/?npc=54205
- [ ] Orphan Matron Seacole https://cata-twinhead.twinstar.cz/?npc=53869

Ally
- [ ] https://www.wowhead.com/quest=29074/a-season-for-celebration
- [ ] https://www.wowhead.com/quest=11356/costumed-orphan-matron
- [ ] https://www.wowhead.com/quest=29054/stink-bombs-away
- [ ] https://www.wowhead.com/quest=29144/clean-up-in-stormwind
- [ ] https://www.wowhead.com/quest=29075/a-time-to-gain
- [ ] https://www.wowhead.com/quest=29371/a-time-to-lose
- [ ] https://www.wowhead.com/quest=12135/let-the-fires-come
- [ ] https://www.wowhead.com/quest=11131/stop-the-fires
- [ ] https://www.wowhead.com/quest=11360/fire-brigade-practice
- [ ] Smash the Pumpkin https://www.wowhead.com/quest=12133/smash-the-pumpkin
- [ ] A Friend in Need https://cata-twinhead.twinstar.cz/?quest=29430
- [ ] Missing Heirlooms https://cata-twinhead.twinstar.cz/?quest=29392
- [ ] Fencing the Goods https://cata-twinhead.twinstar.cz/?quest=29398
- [ ] Shopping Around https://cata-twinhead.twinstar.cz/?quest=29399
- [ ] Taking Precautions https://cata-twinhead.twinstar.cz/?quest=29402
- [ ] The Collector's Agent https://cata-twinhead.twinstar.cz/?quest=29403
- [ ] What Now? https://cata-twinhead.twinstar.cz/?quest=29411
- [ ] The Creepy Crate https://cata-twinhead.twinstar.cz/?quest=29413

horde
- [ ] https://www.wowhead.com/quest=29400/a-season-for-celebration
- [ ] https://www.wowhead.com/quest=11357/masked-orphan-matron
- [ ] https://www.wowhead.com/quest=11361/fire-training
- [ ] Smash the Pumpkin https://www.wowhead.com/quest=12155/smash-the-pumpkin
- [ ] https://www.wowhead.com/quest=29377/a-time-to-break-down
- [ ] A Friend in Need https://cata-twinhead.twinstar.cz/?quest=29431
- [ ] Missing Heirlooms https://cata-twinhead.twinstar.cz/?quest=29415
- [ ] Fencing the Goods https://cata-twinhead.twinstar.cz/?quest=29416
- [ ] Shopping Around https://cata-twinhead.twinstar.cz/?quest=29425
- [ ] Taking Precautions https://cata-twinhead.twinstar.cz/?quest=29426
- [ ] The Collector's Agent https://cata-twinhead.twinstar.cz/?quest=29427
- [ ] What Now? https://cata-twinhead.twinstar.cz/?quest=29428
- [ ] The Creepy Crate https://cata-twinhead.twinstar.cz/?quest=29429

**Achievements**
- [x] Trick or Treat! https://cata-twinhead.twinstar.cz/?achievement=972
- [x] out with it https://cata-twinhead.twinstar.cz/?achievement=288
- [ ] bring me the head of...oh wait https://cata-twinhead.twinstar.cz/?achievement=255
- [ ] The Savior of Hallow's End https://cata-twinhead.twinstar.cz/?achievement=289
- [x] The Mask Task https://cata-twinhead.twinstar.cz/?achievement=979   #4760
- [ ] Hallowed Be Thy Name https://cata-twinhead.twinstar.cz/?achievement=1656 (ally)
- [ ] Hallowed Be Thy Name https://cata-twinhead.twinstar.cz/?achievement=1657 (horde)
- [x] A Mask for All Occasions https://cata-twinhead.twinstar.cz/?achievement=284
- [ ] That Sparkling Smile https://cata-twinhead.twinstar.cz/?achievement=981
- [ ] Rotten Hallow https://cata-twinhead.twinstar.cz/?achievement=1040 (ally)
- [ ] Rotten Hallow https://cata-twinhead.twinstar.cz/?achievement=1041
- [ ] G.N.E.R.D. Rage https://cata-twinhead.twinstar.cz/?achievement=1261
- [ ] Check Your Head https://cata-twinhead.twinstar.cz/?achievement=291
- [ ] The Masquerade https://cata-twinhead.twinstar.cz/?achievement=283
- [ ] Sinister Calling https://cata-twinhead.twinstar.cz/?achievement=292
- [ ] [Tricks and Treats of Kalimdor] https://www.wowhead.com/achievement=965/tricks-and-treats-of-kalimdor (horde)
- [ ] [Tricks and Treats of Kalimdor] https://www.wowhead.com/achievement=963/tricks-and-treats-of-kalimdor (ally)
- [ ] [Tricks and Treats of Eastern Kingdoms] https://www.wowhead.com/achievement=967/tricks-and-treats-of-eastern-kingdoms
- [ ] [Tricks and Treats of Eastern Kingdoms] https://www.wowhead.com/achievement=966/tricks-and-treats-of-eastern-kingdoms
- [x] [Tricks and Treats of Outland] https://www.wowhead.com/achievement=968/tricks-and-treats-of-outland
- [ ] [Tricks and Treats of Outland] https://www.wowhead.com/achievement=969/tricks-and-treats-of-outland
- [ ] [Tricks and Treats of Northrend] https://www.wowhead.com/achievement=5836/tricks-and-treats-of-northrend
- [ ] [Tricks and Treats of Northrend] https://www.wowhead.com/achievement=5835/tricks-and-treats-of-northrend
- [ ] [Tricks and Treats of the Cataclysm] https://www.wowhead.com/achievement=5838/tricks-and-treats-of-the-cataclysm
- [ ] [Tricks and Treats of the Cataclysm] https://www.wowhead.com/achievement=5837/tricks-and-treats-of-the-cataclysm

 **Vender item check** 
- [ ] https://wow.gamepedia.com/Dorothy https://cata-twinhead.twinstar.cz/?npc=53728
- [ ] https://wow.gamepedia.com/Chub https://cata-twinhead.twinstar.cz/?npc=53757

**Ceremonies**

- [ ] Undercity
_At 4:10pm, 8:10pm, and midnight in the Ruins of Lordaeron, Lady Sylvanas Windrunner makes an appearance and gives the following speech:_

_Lady Sylvanas Windrunner yells: Children of the grave, heed my call!
Lady Sylvanas Windrunner yells: In life, we suffered unspeakable tragedies.
Lady Sylvanas Windrunner yells: We watched as our homes were razed to the ground.
Lady Sylvanas Windrunner yells: We cried out in agony as our families were cut down before our eyes.
Lady Sylvanas Windrunner yells: Finally, in the face of such atrocities, we were denied even the release of death.
Lady Sylvanas Windrunner yells: Now, we burn this wickerman as a symbol of our victory against old enemies!
Lady Sylvanas Windrunner yells: We paint our faces with the ash to send a message to new enemies - a declaration to those who fear and revile us as monsters.
Lady Sylvanas Windrunner yells: To those who would question our place in this world...
Lady Sylvanas Windrunner yells: We are NOT monsters! We are NOT the mindless wretches of a ghoul army!
Lady Sylvanas Windrunner yells: No... we are a force even more terrifying...
Lady Sylvanas Windrunner yells: We are the chill in a coward's spine...
Lady Sylvanas Windrunner yells: We are the instruments of an unyielding ire...
Lady Sylvanas Windrunner yells: WE ARE THE FORSAKEN!!!_

- [ ] Stormwind City
_At 4:10pm, 8:10pm, and midnight outside Stormwind City, King Genn Greymane makes an appearance to give a speech._

_Celestine of the Harvest yells: The Wickerman festivities will begin in ten minutes! Please join us just outside the gates of Stormwind City and celebrate Hallow's End!

Genn Greymane yells: Sons and daughters of Gilneas! Friends and allies old and new! Please, come close!
Genn Greymane yells: As you know, Hallow's End is a celebration of transition... of change.
Genn Greymane yells: The people of Gilneas understand the gravity of change all too well.
Genn Greymane yells: For we have endured much... far beyond what any of us could have imagined.
Genn Greymane yells: However, this is a time of neither mourning nor grief.
Genn Greymane yells: It is an opportunity to mock the fearsome - to gaze boldly into the grim unknown and laugh!
Genn Greymane yells: It is a time to celebrate new friends and the future we may forge together.
Genn Greymane yells: New struggles await us with each dawn, and uncertainty weighs upon us all.
Genn Greymane yells: As you stand before me, I pray you cast your burdens behind me.
Genn Greymane yells: Let this wickerman embody any unrest within us.
Genn Greymane yells: With turmoil as tinder, let it blaze; may it temper us against what tomorrow may bring.
Genn Greymane yells: Torches ready!
Genn Greymane yells: Let the flames fly! Hallow's End is upon us!_

![image](https://user-images.githubusercontent.com/39439201/109837105-1f05e600-7c45-11eb-8dc5-5ce0a66eb08f.png)
