### ISSUE TITLE
[Fishing Dailies/Acheivements] Main report 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5181]
**Dailies**
- [x] Jewel Of The Sewers https://www.wowhead.com/quest=13832/jewel-of-the-sewers  -  (#3799)
- [x] Severed Arm https://www.wowhead.com/quest=13836/disarmed - (#4198)
- [x] Blood Is Thicker https://www.wowhead.com/quest=13833/blood-is-thicker - (#5133)
- [x] An Old Favorite https://www.wowhead.com/quest=29359/an-old-favorite - (#4992)
- [x] Tadpole Terror https://www.wowhead.com/quest=29319/tadpole-terror - (#4563)

**Acheivments / missing fish loots items**
**dala random fishing** https://cata-twinhead.twinstar.cz/?spell=60445 (only added coz i see it)

- [x] A Penny For Your Thoughts https://www.wowhead.com/achievement=2094/a-penny-for-your-thoughts - (#4922)
- [x] The Coin Master https://cata-twinhead.twinstar.cz/?achievement=2096 (coins missing)
- [x] There's Gold In That There Fountain https://cata-twinhead.twinstar.cz/?achievement=1957 (coins missing)
- [x] Sewer Carp https://cata-twinhead.twinstar.cz/?area=4560 / https://cata-twinhead.twinstar.cz/?achievement=5478 (missing)
- [x] Fountain Goldfish https://www.wowhead.com/item=43646/fountain-goldfish  (missing) stopping achv
- [x] Shimmering Minnow https://cata-twinhead.twinstar.cz/?item=43647  (missing)
- [x] Slippery Eel https://www.wowhead.com/item=43652/slippery-eel  (missing)
- [x] The fishing diplomat https://www.wowhead.com/achievement=150/the-fishing-diplomat - (#2021)  (fixed on Mfranca PTR)
- [x] Old ironjaw https://cata-twinhead.twinstar.cz/?item=34484 (not dropping in Ironforge) stopping achv
- [x] One That Didn't Get Away https://cata-twinhead.twinstar.cz/?achievement=878 (been checked for %)
- [x] Mr. Pinchy's Magical Crawdad Box https://cata-twinhead.twinstar.cz/?achievement=726
- [ ] Bloodsail Wreckage https://cata-twinhead.twinstar.cz/?object=180901 (not spawning from the other pools like they should) stopping achv  (needs schools all replacing with correct fishing schools) 

**seasonal fishing loot**
- [ ] The Oceanographer https://www.wowhead.com/achievement=5479/the-oceanographer `Winter squid Sept 23-20th March`
- [ ] The Oceanographer https://www.wowhead.com/achievement=5479/the-oceanographer `Summer Bass March 20-Sept 22 `
NOTE: https://www.wowhead.com/item=13756/raw-summer-bass#comments is dropping in Winter months in Tanaris

**Weekly fishing events**
- [ ] Stranglethorn Fishing Extravaganza https://github.com/WoWManiaUK/Blackwing-Lair/issues/5125
- [ ] Kalu'ak Fishing Derby https://github.com/WoWManiaUK/Blackwing-Lair/issues/5156

**Wrong loots** 
- [x] Dalaran fountain  https://github.com/WoWManiaUK/Blackwing-Lair/issues/5157
https://wowwiki-archive.fandom.com/wiki/Dalaran_fountain

**Needs level scaling** 
- [x] https://github.com/WoWManiaUK/Blackwing-Lair/issues/4713  - list you asked for Mfranca https://github.com/WoWManiaUK/Blackwing-Lair/issues/4713#issuecomment-813281100

**Empty fishing loot box** 
- [ ] https://github.com/WoWManiaUK/Blackwing-Lair/issues/5158

**Fishing bug** (client issue)
- [ ] https://github.com/WoWManiaUK/Blackwing-Lair/issues/5135

**Bloodelf Male client crash** (client issue) fixed but not on Reign PTR yet
- [x] https://github.com/WoWManiaUK/Blackwing-Lair/issues/2551
https://github.com/WoWManiaUK/Blackwing-Lair/issues/2551#issuecomment-621712537

**Lucky buff needs testing**
- [x] https://www.wowhead.com/spell=59125/lucky (buff applies, not sure if it works to make player more lucky on coins tho)

- [ ] Lucky buff https://cata-twinhead.twinstar.cz/?issue=10848 (not working as it should)

**Comment by Echinaceax** [comment]
**NOTES**


- [x] Lucky buff (applied)

![image](https://user-images.githubusercontent.com/39439201/114299658-cb48b100-9abc-11eb-907e-fa5dc4672a6a.png)

**Confirmed working** 

![image](https://user-images.githubusercontent.com/39439201/119269085-3e822e80-bbf6-11eb-87fe-d9fcf47d98cf.png)

**Comment by Echinaceax** [comment]
**Update** 

Mr. Pinchy's Magical Crawdad Box
https://cata-twinhead.twinstar.cz/?achievement=726

![image](https://user-images.githubusercontent.com/39439201/137593164-3b228014-a3fa-48f7-80d9-f9952c616b61.png)
