### ISSUE TITLE
[Quest order] Silverpine / Ruins of Gilneas - Main fix order

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5199]
https://wowwiki-archive.fandom.com/wiki/Quest:The_Warchief_Cometh

**Missing npcs plus phasing setting**

- [x] Worgen Commando https://www.wowhead.com/npc=46038/worgen-commando
- [x] Cowering Trooper https://www.wowhead.com/npc=45910/cowering-trooper-rescued
- [x] Forsaken Vanguard https://www.wowhead.com/npc=45882/forsaken-vanguard / https://www.wowhead.com/npc=45882/forsaken-vanguard
- [x] Forsaken Trooper https://www.wowhead.com/search?q=forsaken+trooper ( is on the travel cart ) as well 
- [x] Bloodfang Berserker https://www.wowhead.com/npc=45860/bloodfang-berserker
- [x] Forsaken Sharpshooter https://www.wowhead.com/npc=45376/forsaken-sharpshooter
- [x] Orc Sea Dog https://cata-twinhead.twinstar.cz/?npc=45589 (need 20) 
- [ ] Orc Sea Dog https://cata-twinhead.twinstar.cz/?npc=46057 (missing)
- [x] Deathstalker https://cata-twinhead.twinstar.cz/?npc=44790#
- [x] Apothecary Initiate https://cata-twinhead.twinstar.cz/?npc=44786#
- [x] Apothecary Harrington <General Goods> https://cata-twinhead.twinstar.cz/?npc=45491
- [x] Apothecary Marry <Trade Supplies> https://cata-twinhead.twinstar.cz/?npc=45490
- [x] Apothecary Chase <Alchemy Supplies> https://cata-twinhead.twinstar.cz/?npc=45489
- [ ] Worgen Warbringer <Gilneas Liberation Front> https://cata-twinhead.twinstar.cz/?npc=45996
- [ ] Worgen Sentry https://www.wowhead.com/npc=44987/worgen-sentry 
- [ ] Finn's Gambit  https://cata-twinhead.twinstar.cz/?npc=50949 **Rare**
- [ ] Corpsefeeder https://www.wowhead.com/npc=50814/corpsefeeder **Rare**
- [ ] Gnath  https://www.wowhead.com/npc=51026/gnath **Rare**
- [ ] Kree  https://www.wowhead.com/npc=50330/kree **Rare**
- [ ] Lost Gilnean Wardog  https://www.wowhead.com/npc=51037/lost-gilnean-wardog **Rare**
- [ ] Forsaken Mage https://cata-twinhead.twinstar.cz/?npc=45804
- [ ] Forsaken Mage 2 https://cata-twinhead.twinstar.cz/?npc=46048 **The battlefront**
- [x] High Warlord Cromush https://cata-twinhead.twinstar.cz/?npc=44640
- [ ] Worgen Rebel https://www.wowhead.com/npc=45292/worgen-rebel for (#5187)
- [ ] Bloodfang Scout https://www.wowhead.com/npc=45481/bloodfang-scout (#5187)
- [ ] Worgen Battlemage https://www.wowhead.com/npc=45483/worgen-battlemage (#5187)
- [ ] Worgen Combatant Proxy https://www.wowhead.com/npc=45495/worgen-combatant-proxy (#5187)
- [ ] Worgen Rusher <Gilneas Liberation Front> https://www.wowhead.com/npc=45535/worgen-rusher (**missing**)
- [ ] Deathstalker https://www.wowhead.com/npc=45313/deathstalker (**missing**)
- [ ] Provisioner Angelus <General Goods> https://www.wowhead.com/npc=45484/provisioner-angelus
- [ ] Gilnean Warhound https://www.wowhead.com/npc=45499/gilnean-warhound (#5187)
- [ ] Bloodfang Scout 2 https://www.wowhead.com/npc=45536/bloodfang-scout (#5187)
- [ ] Worgen Battlemage 2 https://www.wowhead.com/npc=45537/worgen-battlemage (#5187) 
- [ ] Gilnean Warhound 2 https://www.wowhead.com/npc=45538/gilnean-warhound (#5187)

**NPCs Abilities/Funtions missing**

- [x] Dark Ranger https://www.wowhead.com/npc=44632/dark-ranger **not moving around camp**
- [x] Worgen renegades https://cata-twinhead.twinstar.cz/?npc=4479 **are not fighing each other**
- [x] Forsaken Troopers https://www.wowhead.com/npc=44791/forsaken-trooper#sounds **are not fighing each other**
- [x] Gorefang (Rare) https://cata-twinhead.twinstar.cz/?npc=12431 **not moving**
- [x] Ferocious Grizzled Bear https://www.wowhead.com/npc=1778/ferocious-grizzled-bear **is not moving**
- [x] Worg https://www.wowhead.com/npc=1765/worg **not moving**
- [x] Rabid Worg https://www.wowhead.com/npc=1766/rabid-worg **not moving**
- [x] Dreadguard https://www.wowhead.com/npc=44911/dreadguard **no waypoint data**
- [ ] Commander Hickley <Innkeeper> https://cata-twinhead.twinstar.cz/?npc=45496 **doesnt have rested XP set in the inn**
- [ ] Innkeeper Bates <Innkeeper> https://cata-twinhead.twinstar.cz/?npc=6739 **doesnt have rested XP set in the inn**
- [ ] Forsaken Trooper https://www.wowhead.com/npc=44733/forsaken-trooper **should be on cart**
- [ ] Horde Engineer https://www.wowhead.com/npc=44734/horde-engineer **should be on cart**
- [x] Inconspicuous Bear https://www.wowhead.com/npc=45750/inconspicuous-bear **not moving**
- [x] Giant Rabid Bear https://www.wowhead.com/npc=1797/giant-rabid-bear **not moving**
- [x] Forest Ettin https://www.wowhead.com/npc=44367/forest-ettin **no waypoint data**
- [x] Bloodfang Scavenger https://www.wowhead.com/npc=44547/bloodfang-scavenger **not moving**
- [x] Skitterweb Lurker https://www.wowhead.com/npc=1781/skitterweb-lurker **not moving**
- [x] Vile Fin Oracle https://www.wowhead.com/npc=1908/vile-fin-oracle **not moving**
- [x] Vile Fin Tidehunter https://www.wowhead.com/npc=1768/vile-fin-tidehunter **not moving**
- [x] Bloodfang Stalker https://www.wowhead.com/npc=45195/bloodfang-stalker **not moving**
- [x] Darktusk Boar https://www.wowhead.com/npc=46575/darktusk-boar **not moving**
- [x] Elemental Servitor https://www.wowhead.com/npc=45711/elemental-servitor **not moving**
- [x] Elemental Servitor https://www.wowhead.com/npc=45711/elemental-servitor **no waypoint data** 
- [x] Aquarius the Unbound (Rare) https://www.wowhead.com/npc=47009/aquarius-the-unbound **no waypoint data** 
- [x] Marsh Crocolisk https://www.wowhead.com/npc=45896/marsh-crocolisk **not moving**
- [x] Gilnean Hound https://www.wowhead.com/npc=45367/gilnean-hound **not moving**
- [x] Highlands Fox https://www.wowhead.com/npc=45335/highlands-fox **not moving**
- [x] Hillsbrad Worgen male https://cata-twinhead.twinstar.cz/?npc=45254
- [x] Hillsbrad Worgen female https://cata-twinhead.twinstar.cz/?npc=45255
- [x] Vile Fin Tidehunter https://www.wowhead.com/npc=46574/vile-fin-tidehunter **not moving**
- [x] Vile Fin Oracle https://www.wowhead.com/npc=46573/vile-fin-oracle **not moving**
- [x] Bloodfang Berserker https://www.wowhead.com/npc=45860/bloodfang-berserker **not moving**
- [x] Hillsbrad Refugee https://cata-twinhead.twinstar.cz/?npc=44954 **no waypoint data** 
- [x] Hillsbrad Refugee https://cata-twinhead.twinstar.cz/?npc=44966 **no waypoint data**
- [x] Forsaken Trooper https://cata-twinhead.twinstar.cz/?npc=46053 **no waypoint data /formation** 
- [x] Forsaken Trooper https://cata-twinhead.twinstar.cz/?npc=46054 **no waypoint data /formation** 
- [ ] Worgen Sentry https://www.wowhead.com/npc=44987/worgen-sentry  **not moving** (only when added)
- [x] Dalaran Summoner https://cata-twinhead.twinstar.cz/?npc=2358#abilities **missing abilies**
- [x] Arcane Remnant https://cata-twinhead.twinstar.cz/?npc=45728 **not moving**
- [x] Dalaran Worker https://cata-twinhead.twinstar.cz/?npc=2628 **not moving**
- [x] Dalaran Worker https://cata-twinhead.twinstar.cz/?npc=2628 **not building** 
- [x] snapjaw https://cata-twinhead.twinstar.cz/?npc=2408 **not moving**
- [ ] Lost Son Of Arugal (Rare) https://www.wowhead.com/npc=47015/lost-son-of-arugal **no waypoint data** https://www.youtube.com/watch?v=rZOGExEDrJM
- [ ] Lost Son Of Arugal (Rare) https://www.wowhead.com/npc=47015/lost-son-of-arugal **Spell not working**
https://www.wowhead.com/spell=87569/a-chill-runs-up-your-spine
- [ ]  "Salty" Rocka / "Salty" Gorgar #5254 **YELL text arguement** 
- [ ] Orc sea dog cooking banter https://www.wowhead.com/npc=44913/orc-sea-dog  **random txt** 

**Missing Quotes** 

- [ ] Forsaken Trooper https://wowpedia.fandom.com/wiki/Forsaken_Trooper **Silverpine Forest**
- [ ] Forsaken Trooper https://wowpedia.fandom.com/wiki/Forsaken_Trooper **Fenris Isle**

**Cart and function** 

- [ ] Spawned but not moving and no text set https://www.youtube.com/watch?v=mxPq4cX8XDo
- [ ] Subdued Forest Ettin and Horde coffin Hauler https://www.wow-freakz.com/npc_finder.php?npc=44737&name=subdued-forest-ettin / Aura https://www.wow-freakz.com/spells.php?spell=46598&name=ride-vehicle-hardcoded / https://www.wow-freakz.com/npc_finder.php?npc=44764&name=horde-coffin-hauler

**missing objects**

- [ ] Forsaken Catapults https://cata-twinhead.twinstar.cz/?npc=45282 - https://www.wowhead.com/search?q=forsaken+catapult

**Missing items/weapons**

- [x] Forsaken Trooper https://www.wowhead.com/npc=44791/forsaken-trooper
- [x] Forsaken Trooper https://cata-twinhead.twinstar.cz/?npc=46053 
- [x] Forsaken Trooper https://cata-twinhead.twinstar.cz/?npc=46054 

**Quests**

- [x] Quest:Warchief's Command: Silverpine Forest! https://cata-twinhead.twinstar.cz/?quest=26964  (#5241)
- [x] The Warchief Cometh #4478 (full scripting needed)
- [x] Agony Abounds #5136 
- [x] Guts and Gore #5138 and #5137 (npc fixed)
- [x] The Gilneas Liberation Front
- [x] Iterating Upon Success #5137 (npc fixed) **needs dialog and full scripting**  #5242
- [x] Dangerous Intentions #5139
- [x] Waiting to Exsanguinate #5140   2 npc and cutscene missing 
- [x] Belmont's Report
- [x] The Warchief's Fleet
- [x] Playing Dirty
- [ ] Steel Thunder #5144 (needs Orc sea pup) 
- [x] Give 'em Hell! #5143 (npc not seen by players, so cant pick up quest)
- [x] It's Only Poisonous if You Ingest It
- [ ] Lost in the Darkness #5145 
- [ ] Deeper into Darkness (cant get this quest until #5145 is fixed)
- [x] Orcs are in Order #5141
- [ ] Rise, Forsaken #5147
- [ ] No Escape #5148 (needs #5147 fixing first)
- [ ] Lordaeron #5243
- [ ] Honor the Dead #5149 
- [ ] Hair of the Dog #5146 
- [x] Reinforcements from Fenris
- [ ] The Waters Run Red... #5150
- [ ] Excising the Taint #5151
- [x] Seek and Destroy
- [x] Cornered and Crushed! #5152 
- [ ] Nowhere to Run #5186 
- [ ] To Forsaken Forward Command #5256
- [ ] Losing Ground #5153 and #5187 (npc fixed)
- [ ] In Time, All Will Be Revealed #5188
- [ ] The F.C.D. https://www.wowhead.com/quest=27345/the-f-c-d (missing object)
- [ ] Korok the Colossus #5190 
- [x] Break in Communications: Dreadwatch Outpost #5153 
- [x] Break in Communications: Rutsak's Guard #5154 
- [x] On Whose Orders? #5154 
- [ ] What Tomorrow Brings #5193 
- [ ] Fall Back! #5195
- [ ] A Man Named Godfrey #5194 
- [ ] Resistance is Futile #5196 
- [ ] The Great Escape #5197
- [ ] Rise, Godfrey (need to retest when npc is added)  https://cata-twinhead.twinstar.cz/?spell=85149 - https://www.wow-freakz.com/database.php?search=lord+godfrey **video** https://www.youtube.com/watch?v=M6BxUHBsva0  (#5255)
- [x] Breaking the Barrier (quest works once quest added)
- [x] Unyielding Servitors 
- [x] Dalar Dawnweaver
- [x] Relios the Relic Keeper
- [x] Only One May Enter (quest works once the delivery npc is spawned)
- [x] Transdimensional Warfare: Chapter I
- [ ] Transdimensional Warfare: Chapter II #5202
- [ ] Transdimensional Warfare: Chapter III #5203 
- [ ] Taking the Battlefront #5204
- [ ] Of No Consequence #5205
- [ ] Lessons in Fear #5206
- [ ] Pyrewood's Fall #5209 
- [x] 7th Legion Battle Plans #5210
- [x] Sowing Discord #5210
- [x] On Her Majesty's Secret Service #5212
- [ ] Cities in Dust #5213
- [ ] Empire of Dirt

**Flight paths**

- [x] https://github.com/WoWManiaUK/Blackwing-Lair/issues/5198

**Missing animations**
- [ ] missing burning buildings after the zone has been completely finished (Pyrewood's)
- [ ] missing Fires (rear guard beach area)

should look like this 

![silv21 burning buildings](https://user-images.githubusercontent.com/39439201/116058978-accbe380-a680-11eb-938c-47c2931ddb9e.jpg)

**notes**

- [ ] the battle at forsaken front is not there , missing npcs, missing catapults, missing flighting

![image](https://user-images.githubusercontent.com/39439201/116057612-42ff0a00-a67f-11eb-81d7-a1d2187b0728.png)

Battle should look like this 

![silv22 battle ](https://user-images.githubusercontent.com/39439201/116059394-14822e80-a681-11eb-8a94-a414b0740fd9.jpg)

**Phase out after the last quest** 
https://wowpedia.fandom.com/wiki/Forsaken_Front
![image](https://user-images.githubusercontent.com/39439201/116082718-07266d80-a69c-11eb-85e6-36bcdba45919.png)
https://wowpedia.fandom.com/wiki/Battlefront
![image](https://user-images.githubusercontent.com/39439201/116082865-3046fe00-a69c-11eb-827b-b0e57099477b.png)
https://wowpedia.fandom.com/wiki/7th_Legion_Base_Camp
![image](https://user-images.githubusercontent.com/39439201/116083028-6dab8b80-a69c-11eb-88b9-88838ed50af2.png)
https://wowpedia.fandom.com/wiki/Gilneas_Liberation_Front_Base_Camp
![image](https://user-images.githubusercontent.com/39439201/116083120-8ddb4a80-a69c-11eb-95eb-464fd11b845f.png)

**Comment by mfranca0009** [comment]
Silverpine Forest / Ruins of Gilneas quest ordering should now be all set and ready for next update 👍
