### ISSUE TITLE
[QUEST] Icecrown quests main report - Icecrown

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5318]
### NOT FINISHED YET

- [ ] Quest order needs fixing first before we can continiue with the rest of the report 
Ive done what I can for now @mfranca0009 https://github.com/WoWManiaUK/Blackwing-Lair/issues/5318#issuecomment-913138847 

**Link**

Source https://wowpedia.fandom.com/wiki/Icecrown_quests
Quest order wrong https://github.com/WoWManiaUK/Blackwing-Lair/issues/5318#issuecomment-913138847 
quest givers phasing https://github.com/WoWManiaUK/Blackwing-Lair/issues/5318#issuecomment-913501109

- [x] #5331
- [x] Judgment Day Comes!
- [x] Honor Above All Else
**All three of:**
- [x] Scourge Tactics
- [x] Curing The Incurable
- [x] Defending The Vanguard
- [x] If There Are Survivors...
- [ ] Into The Wild Green Yonder #5184
- [x] #5333
- [ ] The Last Line Of Defense #4589 
- [x] Once More Unto The Breach, Hero
**Valley of Echoes**
**Complete both to continue:**
- [x] The Purging Of Scourgeholme
- [x] The Scourgestone
- [x] The Air Stands Still
**Side quests:**
- [x] The Restless Dead #5319
- [x] The Stone That Started A Revolution
- [x] It Could Kill Us All
**After completing the above steps, including side quests:**
- [x] Into The Frozen Heart Of Northrend
- [ ] The Battle For Crusaders' Pinnacle #4593
- [ ] The Crusaders' Pinnacle
**Crusader Bridenbrad**
- [x] A Tale of Valor
- [x] A Hero Remains
- [ ] The Keeper's Favor #5320
- [ ] Hope Within the Emerald Nightmare #4732
- [x] The Boon of Remulos
- [x] Time Yet Remains
- [x] The Touch of an Aspect
- [x] Dahlia's Tears
- [x] The Boon of Alexstrasza
- [x] Hope Yet Remains
- [x] The Will of the Naaru
- [x] The Boon of A'dal
- [x]  Light Within the Darkness
**Skybreaker (Ally)**
- [ ]  The Skybreaker 
**Ymirheim (ally)**
- [ ]  Get to Ymirheim!
- [ ]  King of the Mountain
- [ ]  Joining the Assault
- [ ]  Assault by Air
- [ ]  Assault by Ground
- [ ]  Slaves to Saronite
- [ ] ] Blood of the Chosen
**Broken Front (ally)**
- [ ] The Broken Front
- [ ]  Finish Me!
- [ ]  No Mercy!
**After The Broken Front (ally)**
- [ ]  ...All the Help We Can Get.
- [ ]  Poke and Prod
- [ ]  That's Abominable! (A [25-30 Daily] That's Abominable!)
- [ ]  Against the Giants
- [ ]  Coprous the Defiled
- [ ]  Basic Chemistry (Daily version)
**After The Broken Front: (ally)**
- [ ] Your Attention, Please
- [ ] Borrowed Technology
- [ ] The Solution Solution
- [ ] Killohertz
- [ ] Leading the Charge
- [ ] Static Shock Troops: the Bombardment
- [ ] Watts My Target
- [ ] Putting the Hertz: The Valley of Lost Hope
**Aldur'thar: (ally)**
- [ ] Sneak Preview
- [ ] Drag and Drop (Daily version)
- [ ] Not a Bug (Daily version)
- [ ] Need More Info
- [ ] No Rest For The Wicked (Daily version)
- [ ] The Ironwall Rampart
- [x] Before the Gate of Horror
- [x] Shatter the Shards
- [x] The Guardians of Corp'rethar
- [ ] Chain of Command
- [ ] Cannot Reproduce
- [ ] Retest Now (Daily version)
**Valley of Fallen Heroes, after Need More Info: (ally)**
- [ ] Raise the Barricades
- [ ] Bloodspattered Banners
- [ ] Get the Message (Daily version)
**Orgrim's Hammer (horde)**
- [x] Orgrim's Hammer
**Ymirheim (horde)**
- [x] Get to Ymirheim!
- [x] King of the Mountain
- [x] Joining the Assault
- [ ] Assault by Air
- [ ] Assault by Ground
- [x] Slaves to Saronite
- [x] Blood of the Chosen
**Broken Front (horde)**
- [ ] The Broken Front  #5321
- [x] Avenge Me! (optional)
- [ ] Make Them Pay! (pvp daily)
**After the Broken Front (horde)**
- [x] Takes One to Know One
- [x] Poke and Prod
- [x] That's Abominable! (H [25-30 Daily] That's Abominable!)
- [x] Against the Giants
- [x] Coprous the Defiled
- [ ] Basic Chemistry  #5322
- [x] Neutralizing the Plague
**After the Broken Front (horde)**
- [x] Good For Something?
- [x] Volatility (H [25-30] Volatility) #5323
- [x] Green Technology `This quest was marked obsolete by Blizzard and cannot be obtained or completed.`
- [x] Fringe Science Benefits `The subject of this article was removed from World of Warcraft in patch 4.1.0.`
- [x] Riding the Wavelength: The Bombardment `was removed from World of Warcraft in patch 4.1.0.`
- [x] Amped for Revolt! `The The subject of this article has been removed from World of Warcraft.`
- [x] Total Ohmage: The Valley of Lost Hope! `was removed from World of Warcraft in patch 4.1.0.`
**Aldur'thar: (horde)**
- [x] Sneak Preview
- [x] Drag and Drop (H [25-30 Daily] Drag and Drop)
- [x] Not a Bug (H [25-30 Daily] Not a Bug)
- [x] Need More Info
- [x] No Rest For The Wicked (H [25-30G5 Daily] No Rest For The Wicked)
- [x] The Ironwall Rampart
- [ ] Before the Gate of Horror
- [ ] The Guardians of Corp'rethar
- [x] Shatter the Shards
- [x] Chain of Command
- [x] Cannot Reproduce
- [x] Retest Now (H [25-30 Daily] Retest Now)
**Valley of Fallen Heroes: (horde)**
- [x] Raise the Barricades
- [x] Bloodspattered Banners
- [x] Blinding the Eyes in the Sky (H [25-30 Daily] Keeping the Alliance Blind)
**Saronite Mines** 
- [x] Mind Tricks
**Malykriss: The Vile Hold**
- [x] It's All Fun and Games `doable when you type /target The Ocular`
- [x] I Have an Idea, But First...
- [x] Free Your Mind
- [x]  If He Cannot Be Turned
- [x] The Shadow Vault
- [x] The Duke
- [ ] Honor Challenge https://www.wowhead.com/quest=12939/honor-challenge `quest item doesnt challenge the npcs `
- [x] Shadow Vault Decree
- [x] Get the Key
- [x] Let the Baron Know
**After Let The Baron Know:**
- [x] Crush Dem Vrykuls!
- [x] Vile Like Fire! (flight issue) `but can be completed`
**After Let The Baron Know:**
- [ ] Vaelen Has Returned `quest not offered `
- [ ] Ebon Blade Prisoners `Quest not offered because of the above quest`
**After Let The Baron Know:**
- [ ] Leave Our Mark
- [ ] Vandalizing Jotunheim
- [ ] Shoot 'Em Up
**Keritose Bloodblade**
- [x] Parting Gifts
**Complete all of the following:**
- [ ] From Whence They Came
- [ ] An Undead's Best Friend
- [ ] Honor is for the Weak
**Complete both of the following:**
- [ ] Seeds of Chaos
- [ ] Amidst the Confusion
- [ ] Vereth the Cunning
- [ ] New Recruit
- [ ] The Vile Hold
**Complete all of the following:**
- [ ] Generosity Abounds
- [ ] Matchmaker
- [ ] Stunning View #5325
**Complete all of the following:**
- [ ] The Rider of the Unholy
- [ ] The Rider of Frost
- [ ] The Rider of Blood
- [ ] The Fate of Bloodbane
**Teaching the Meaning of Fear**
**After If He Cannot Be Turned:**
- [x] Blackwatch
- [x] Where Are They Coming From?
- [x] Destroying the Altars & N [25-30] Death's Gaze
- [x] Spill Their Blood
- [x] Jagged Shards
- [x] I'm Smelting... Smelting! & N [25-30] The Runesmiths of Malykriss
- [x] A Visit to the Doctor `no quest credit for Help Patches kill Doctor Sabnok` `player update said gaven on 2nd try`
- [ ] By Fire Be Purged (optional)
- [x] Killing Two Scourge With One Skeleton `quest not offered`  `update player confirmed quest given when other quest completed`
- [ ] He's Gone to Pieces `Wrong phase to see NPC Corpulent horror `
- [ ] Putting Olakin Back Together Again
- [ ] The Flesh Giant Champion
**Father Kamaros**
- [ ]  I'm Not Dead Yet! (escort) 
 **or** 
- [ ] Let's Get Out of Here! (horde)
- [ ] Let's Get Out of Here (escort) (ally)
**The Unthinkable**
**After The Shadow Vault:**
- [ ] Eliminate the Competition
- [ ] The Bone Witch
- [ ] Reading the Bones (Repeatable version)
- [ ] Deep in the Bowels of The Underhalls
**Side quest: N [25-30] Revenge for the Vargul**
- [ ] The Sum is Greater than the Parts #5266
- [ ] The Art of Being a Water Terror
- [ ] Through the Eye
- [ ] Find the Ancient Hero
- [ ] Not-So-Honorable Combat
- [ ] Banshee's Revenge
- [ ] Battle at Valhalas
- [ ] Battle at Valhalas: Fallen Heroes
- [ ] Battle at Valhalas: Khit'rix the Dark Master
- [ ] Battle at Valhalas: The Return of Sigrid Iceborn
- [ ] Battle at Valhalas: Carnage!
- [ ] Battle at Valhalas: Thane Deathblow
- [ ] Battle at Valhalas: Final Challenge
**Death's Rise**
**After Vandalizing Jotunheim:**
- [x] To the Rise with all Due Haste!
- [x] The Story Thus Far...
**Optional daily side quests:**
- [ ]  Intelligence Gathering
- [ ] From Their Corpses, Rise!
- [x] Blood in the Water
- [x] You'll Need a Gryphon
- [ ] No Fly Zone (flight issue) `but can be completed`
**Dropped:**
- [ ] The Grand (Admiral's) Plan
- [ ] In Strict Confidence
- [ ] Second Chances
- [ ] The Admiral Revealed
**Icecrown Citadel** (ally/horde)
- [x] The Shadow Vault /  The Shadow Vault: 
- [x] Exploiting an Opening / Opportunity
- [x] Securing the Perimeter / Establishing Superiority `first quest not offered`
- [x] Set it Off! / Blow it Up! `first quest not offered`
- [x]  A Short Fuse
- [x] A Voice in the Dark
- [x] Time to Hide
- [x] Return to the Surface
- [ ] Field Repairs
**First Legion Forward Camp**
**After A** 
- [x] Field Repairs / (Horde):
- [x] Do Your Worst `quest doable, but phasing issue`
- [ ] Army of the Damned `no vehicle bar given` https://www.wowhead.com/quest=13236/army-of-the-damned
- [x] Futility
- [ ] Sindragosa's Fall / Cradle of the Frostbrood `first quest not offered `
**Sindragosa's Fall**
- [ ] Where Dragons Fell
- [ ] Time for Answers
- [ ] The Hunter and the Prince
- [ ] Knowledge is a Terrible Burden
- [ ] Tirion's Help / H [25-30] `Argent Aid offered to early` `first quest not offered`
- [ ] Tirion's Gambit #4733 `offered to early`

**Comment by Echinaceax** [comment]
### First issue ive seen quest order wrong `Horde`

quests offered to early 

https://www.wowhead.com/quest=13238/good-for-something
https://www.wowhead.com/quest=13260/takes-one-to-know-one

![quest to early ](https://user-images.githubusercontent.com/39439201/132125613-f91db940-7297-4256-8937-e82b1e7f44ec.jpg)


this is what is screwing players phasing 
2nd quest is https://www.wowhead.com/quest=13227/judgment-day-comes and what i think is happening is players are taking the 2 early quest and its messing their phasing

**Advice for now** 
If players can follow the quest order correctly from here https://wowpedia.fandom.com/wiki/Icecrown_quests then they will be phased correctly throughout the questline in Icecrown until fixes are made for the quest order 

and use BG command and GMs for issues that they encounter on the way

**Comment by Echinaceax** [comment]
### 2nd issue Phasing issue stops `Horde`

- [x] If players do the questline in correct order  https://www.wowhead.com/quest=13141/the-battle-for-crusaders-pinnacle quest the phasing is fixed for #4593

**Comment by Echinaceax** [comment]
### 3rd issue NPC phasing `Horde`

- [ ] As players go through the questline picking up quests from on ship, when the ship is moving the npc delivery is sometimes not there 


https://www.wowhead.com/npc=29795/koltira-deathweaver
![image](https://user-images.githubusercontent.com/39439201/132195392-f9609605-97d7-407b-98ef-c45d599320c4.png)

- [ ] After completing https://www.wowhead.com/quest=13366/need-more-info the NPC is not phasing back like the other npcs.

NPC shows Hes spawned but invalid target map or coordinates

![image](https://user-images.githubusercontent.com/39439201/132197634-c7166de9-5431-4b7b-864f-e0e48d25ec17.png)

**Comment by Echinaceax** [comment]
### 4th totally messed up `Alliance `

- [ ] After picking up first quest from Dalaran and delevering quest back all NPC and dailies already active all at same time 
- [ ] NPC float way on relog too 

![image](https://user-images.githubusercontent.com/39439201/132533305-bc162d92-238c-4539-b293-cc5e9fedef2a.png)
